//! Fowler corpus generator used by `tools/tests/main.zig`.
//! It consumes Rust's Fowler TOML files via `zig-toml` and emits
//! deterministic Zig case tables in `tests/fowler/`.

const std = @import("std");
const toml = @import("toml");

const SuiteSpec = struct {
    source_path: []const u8,
    output_path: []const u8,
};

const RawDoc = struct {
    @"test": []const RawCase,
};

const RawCase = struct {
    name: []const u8,
    regex: []const u8,
    haystack: []const u8,
    matches: []const []const []const i64,
    @"match-limit": usize = 1,
    compiles: ?bool = null,
    anchored: bool = false,
    unescape: bool = false,
    @"case-insensitive": bool = false,
};

const CapKey = enum {
    // Syntax.
    dot,
    alternation,
    noncapture_group,
    named_capture_group,
    rep_zero_or_one,
    rep_zero_or_more,
    rep_one_or_more,
    rep_exact,
    rep_min,
    rep_range,
    rep_lazy,
    rep_possessive,
    class_simple,
    class_range,
    class_negated,
    class_posix,
    class_perl,
    class_unicode_property,
    class_unicode_script_or_block,
    anchor_line_start,
    anchor_line_end,
    anchor_text_start,
    anchor_text_end,
    word_boundary,
    not_word_boundary,
    escape_c_style,
    escape_hex_byte,
    escape_hex_braced,
    escape_unicode_short,
    escape_unicode_long,
    escape_octal,
    escape_literal_mode,
    inline_flags_global,
    inline_flags_scoped,
    inline_flags_toggle,
    ignore_case,
    multi_line,
    dot_matches_new_line,
    swap_greed,
    unicode_mode,
    crlf_mode,
    lookahead,
    negative_lookahead,
    lookbehind,
    negative_lookbehind,
    backref_numeric,
    backref_named,

    // Harness / directives.
    case_unescape,
    case_match_limit,
    case_compiles_true,
    case_compiles_false,
    input_anchored,
};

const CapKeySet = std.EnumSet(CapKey);

pub fn run() !void {
    const suites = [_]SuiteSpec{
        .{
            .source_path = "tests/fowler/data/basic.toml",
            .output_path = "tests/fowler/basic.zig",
        },
        .{
            .source_path = "tests/fowler/data/repetition.toml",
            .output_path = "tests/fowler/repetition.zig",
        },
        .{
            .source_path = "tests/fowler/data/nullsubexpr.toml",
            .output_path = "tests/fowler/nullsubexpr.zig",
        },
    };

    var total: usize = 0;
    for (suites) |suite| {
        const count = try generateSuite(suite);
        total += count;
        std.debug.print(
            "generated {s} from {s} ({d} cases)\n",
            .{ suite.output_path, suite.source_path, count },
        );
    }
    std.debug.print("fowler generation complete ({d} total cases)\n", .{total});
}

fn generateSuite(spec: SuiteSpec) !usize {
    const cwd = std.fs.cwd();
    const input = try cwd.readFileAlloc(
        std.heap.page_allocator,
        spec.source_path,
        std.math.maxInt(usize),
    );
    defer std.heap.page_allocator.free(input);

    var parser = toml.Parser(RawDoc).init(std.heap.page_allocator);
    defer parser.deinit();

    const parsed = try parser.parseString(input);
    defer parsed.deinit();

    try writeGeneratedFile(spec, parsed.value.@"test");
    return parsed.value.@"test".len;
}

fn writeGeneratedFile(spec: SuiteSpec, cases: []const RawCase) !void {
    const cwd = std.fs.cwd();
    const out_dir = std.fs.path.dirname(spec.output_path) orelse return error.InvalidOutputPath;
    try cwd.makePath(out_dir);

    const file = try cwd.createFile(spec.output_path, .{});
    defer file.close();

    var file_writer_buf: [8192]u8 = undefined;
    var file_writer = file.writer(&file_writer_buf);
    const w = &file_writer.interface;

    try w.writeAll("//! GENERATED by `zig build gen-tests -- fowler`.\n");
    try w.print("//! Source: {s}\n", .{spec.source_path});
    try w.writeAll("//! DO NOT EDIT.\n\n");
    try w.writeAll("const harness = @import(\"../harness.zig\");\n");
    try w.writeAll("const runner = harness.runner;\n");
    try w.writeAll("const caps = harness.capabilities;\n");
    try w.writeAll("const Match = @import(\"export_test\").Regex.Match;\n\n");
    try w.writeAll("pub const cases = [_]runner.Case{\n");
    for (cases) |tc| {
        try writeCase(w, tc);
    }
    try w.writeAll("};\n");
    try w.flush();
}

fn writeCase(w: anytype, tc: RawCase) !void {
    try w.writeAll("    .{\n");
    try w.writeAll("        .name = ");
    try writeEscapedZigString(w, tc.name);
    try w.writeAll(",\n");

    try w.writeAll("        .pattern = ");
    try writeEscapedZigString(w, tc.regex);
    try w.writeAll(",\n");

    try w.writeAll("        .haystack = ");
    try writeEscapedZigString(w, tc.haystack);
    try w.writeAll(",\n");

    const empty_groups = &[_][]const i64{};
    const groups = if (tc.matches.len > 0) tc.matches[0] else empty_groups;

    try w.writeAll("        .expected = &[_]?Match{");
    if (groups.len == 0) {
        try w.writeAll("},\n");
    } else {
        try w.writeAll("\n");
        for (groups) |group| {
            try w.writeAll("            ");
            if (group.len == 0) {
                try w.writeAll("null,\n");
                continue;
            }
            if (group.len != 2) return error.InvalidMatchGroupShape;
            if (group[0] < 0 or group[1] < 0) return error.InvalidMatchGroupShape;
            const start: usize = @intCast(group[0]);
            const end: usize = @intCast(group[1]);
            try w.print(".{{ .start = {d}, .end = {d} }},\n", .{ start, end });
        }
        try w.writeAll("        },\n");
    }

    var requires = inferPatternCaps(tc.regex);
    if (tc.anchored) requires.insert(.input_anchored);
    if (tc.unescape) requires.insert(.case_unescape);
    // TODO: Pass down Regex.Options from case directives (e.g. case-insensitive)
    // once Regex.Options is fully incorporated in the harness path.
    if (tc.@"case-insensitive") requires.insert(.ignore_case);
    if (tc.@"match-limit" != 1) requires.insert(.case_match_limit);
    if (tc.compiles) |compiles| {
        requires.insert(if (compiles) .case_compiles_true else .case_compiles_false);
    }

    if (requires.count() > 0) {
        try w.writeAll("        .requires = caps.requires(.{ ");
        var first = true;
        inline for (std.meta.fields(CapKey)) |field| {
            const cap: CapKey = @enumFromInt(field.value);
            if (requires.contains(cap)) {
                try writeCapKey(w, &first, cap);
            }
        }
        try w.writeAll(" }),\n");
    }

    try w.writeAll("    },\n");
}

fn writeCapKey(w: anytype, first: *bool, cap: CapKey) !void {
    if (!first.*) try w.writeAll(", ");
    first.* = false;
    try w.print(".{s} = true", .{@tagName(cap)});
}

fn writeEscapedZigString(w: anytype, bytes: []const u8) !void {
    try w.writeByte('"');
    for (bytes) |b| {
        switch (b) {
            '\\' => try w.writeAll("\\\\"),
            '"' => try w.writeAll("\\\""),
            '\n' => try w.writeAll("\\n"),
            '\r' => try w.writeAll("\\r"),
            '\t' => try w.writeAll("\\t"),
            else => {
                if (b < 0x20 or b > 0x7e) {
                    try w.print("\\x{X:0>2}", .{b});
                } else {
                    try w.writeByte(b);
                }
            },
        }
    }
    try w.writeByte('"');
}

fn inferPatternCaps(pattern: []const u8) CapKeySet {
    var caps = CapKeySet.initEmpty();
    var in_class = false;
    var class_started = false;
    var class_first = false;
    var escaped = false;

    var i: usize = 0;
    while (i < pattern.len) : (i += 1) {
        const c = pattern[i];
        if (escaped) {
            i = handleEscapeAt(pattern, i, &caps);
            escaped = false;
            continue;
        }
        if (c == '\\') {
            escaped = true;
            continue;
        }

        if (in_class) {
            if (class_first) {
                class_first = false;
                if (c == '^') {
                    caps.insert(.class_negated);
                    continue;
                }
            }

            if (c == '[' and i + 1 < pattern.len and pattern[i + 1] == ':') {
                caps.insert(.class_posix);
            } else if (c == '-' and i + 1 < pattern.len and pattern[i + 1] != ']' and class_started) {
                caps.insert(.class_range);
            } else if (c == ']' and class_started) {
                in_class = false;
                continue;
            }

            class_started = true;
            continue;
        }

        switch (c) {
            '[' => {
                in_class = true;
                class_started = false;
                class_first = true;
                caps.insert(.class_simple);
            },
            '.' => caps.insert(.dot),
            '|' => caps.insert(.alternation),
            '^' => caps.insert(.anchor_line_start),
            '$' => caps.insert(.anchor_line_end),
            '(' => handleGroup(pattern, &i, &caps),
            '?' => {
                caps.insert(.rep_zero_or_one);
                if (i + 1 < pattern.len and pattern[i + 1] == '+') caps.insert(.rep_possessive);
            },
            '*' => {
                caps.insert(.rep_zero_or_more);
                if (i + 1 < pattern.len and pattern[i + 1] == '?') caps.insert(.rep_lazy);
                if (i + 1 < pattern.len and pattern[i + 1] == '+') caps.insert(.rep_possessive);
            },
            '+' => {
                caps.insert(.rep_one_or_more);
                if (i + 1 < pattern.len and pattern[i + 1] == '?') caps.insert(.rep_lazy);
                if (i + 1 < pattern.len and pattern[i + 1] == '+') caps.insert(.rep_possessive);
            },
            '{' => handleRepeatRange(pattern, &i, &caps),
            else => {},
        }
    }

    return caps;
}

fn handleGroup(pattern: []const u8, i: *usize, caps: *CapKeySet) void {
    if (i.* + 1 >= pattern.len or pattern[i.* + 1] != '?') return;
    if (i.* + 2 >= pattern.len) return;

    const marker = pattern[i.* + 2];
    switch (marker) {
        ':' => {
            caps.insert(.noncapture_group);
            return;
        },
        '=' => {
            caps.insert(.lookahead);
            return;
        },
        '!' => {
            caps.insert(.negative_lookahead);
            return;
        },
        '<' => {
            if (i.* + 3 < pattern.len and pattern[i.* + 3] == '=') {
                caps.insert(.lookbehind);
                return;
            }
            if (i.* + 3 < pattern.len and pattern[i.* + 3] == '!') {
                caps.insert(.negative_lookbehind);
                return;
            }
            return;
        },
        'P' => {
            if (i.* + 3 < pattern.len and pattern[i.* + 3] == '<') {
                caps.insert(.named_capture_group);
            }
            return;
        },
        else => {},
    }

    var j = i.* + 2;
    var saw_flag = false;
    var saw_toggle = false;
    while (j < pattern.len) : (j += 1) {
        const c = pattern[j];
        if (c == ':') {
            caps.insert(.inline_flags_scoped);
            if (saw_toggle) caps.insert(.inline_flags_toggle);
            i.* = j;
            return;
        }
        if (c == ')') {
            if (saw_flag) caps.insert(.inline_flags_global);
            if (saw_toggle) caps.insert(.inline_flags_toggle);
            i.* = j;
            return;
        }
        if (c == '-') {
            saw_toggle = true;
            continue;
        }
        if (c == 'i' or c == 'm' or c == 's' or c == 'U' or c == 'u' or c == 'R') {
            saw_flag = true;
            switch (c) {
                'i' => caps.insert(.ignore_case),
                'm' => caps.insert(.multi_line),
                's' => caps.insert(.dot_matches_new_line),
                'U' => caps.insert(.swap_greed),
                'u' => caps.insert(.unicode_mode),
                'R' => caps.insert(.crlf_mode),
                else => unreachable,
            }
            continue;
        }
        break;
    }
}

fn handleRepeatRange(pattern: []const u8, i: *usize, caps: *CapKeySet) void {
    var j = i.* + 1;
    while (j < pattern.len and pattern[j] != '}') : (j += 1) {}
    if (j >= pattern.len) return;

    const body = pattern[i.* + 1 .. j];
    if (body.len == 0) return;

    const comma = std.mem.indexOfScalar(u8, body, ',');
    if (comma == null) {
        caps.insert(.rep_exact);
    } else if (comma.? + 1 == body.len) {
        caps.insert(.rep_min);
    } else {
        caps.insert(.rep_range);
    }

    if (j + 1 < pattern.len and pattern[j + 1] == '?') caps.insert(.rep_lazy);
    if (j + 1 < pattern.len and pattern[j + 1] == '+') caps.insert(.rep_possessive);
    i.* = j;
}

fn handleEscapeAt(pattern: []const u8, index: usize, caps: *CapKeySet) usize {
    var i = index;
    const c = pattern[i];
    if (c >= '1' and c <= '9') {
        caps.insert(.backref_numeric);
        if (c <= '7') caps.insert(.escape_octal);
        return i;
    }
    if (c == '0') {
        caps.insert(.escape_octal);
        return i;
    }

    switch (c) {
        'A' => caps.insert(.anchor_text_start),
        'z' => caps.insert(.anchor_text_end),
        'b' => caps.insert(.word_boundary),
        'B' => caps.insert(.not_word_boundary),
        'd', 'D', 'w', 'W', 's', 'S' => caps.insert(.class_perl),
        'x' => {
            if (i + 1 < pattern.len and pattern[i + 1] == '{') {
                caps.insert(.escape_hex_braced);
                if (consumeBracedEscape(pattern, i + 1)) |end| i = end;
            } else {
                caps.insert(.escape_hex_byte);
            }
        },
        'u' => caps.insert(.escape_unicode_short),
        'U' => caps.insert(.escape_unicode_long),
        'a', 'f', 'n', 'r', 't', 'v' => caps.insert(.escape_c_style),
        'Q', 'E' => caps.insert(.escape_literal_mode),
        'p', 'P' => {
            caps.insert(.class_unicode_property);
            if (i + 1 < pattern.len and pattern[i + 1] == '{') {
                const end = consumeBracedEscape(pattern, i + 1) orelse return i;
                const content = pattern[i + 2 .. end];
                if (isUnicodeScriptOrBlock(content)) caps.insert(.class_unicode_script_or_block);
                i = end;
            }
        },
        'k' => {
            if (i + 1 < pattern.len and pattern[i + 1] == '<') caps.insert(.backref_named);
        },
        else => {},
    }
    return i;
}

fn consumeBracedEscape(pattern: []const u8, open_index: usize) ?usize {
    if (pattern[open_index] != '{') return null;
    var i = open_index + 1;
    while (i < pattern.len) : (i += 1) {
        if (pattern[i] == '}') return i;
    }
    return null;
}

fn isUnicodeScriptOrBlock(name: []const u8) bool {
    if (name.len == 0) return false;
    if (std.mem.startsWith(u8, name, "sc=") or std.mem.startsWith(u8, name, "scx=")) return true;
    if (std.mem.startsWith(u8, name, "script=") or std.mem.startsWith(u8, name, "Script=")) return true;
    if (std.mem.startsWith(u8, name, "blk=") or std.mem.startsWith(u8, name, "block=")) return true;
    if (std.mem.startsWith(u8, name, "In")) return true;
    return false;
}
