//! GENERATED by `zig build gen-tests -- fowler`.
//! Source: tests/fowler/data/basic.toml
//! DO NOT EDIT.

const std = @import("std");
const gpa = std.testing.allocator;
const harness = @import("../harness.zig");
const exec = harness.execute;
const caps = harness.capabilities;
const root = @import("root");
const Match = @import("export_test").Regex.Match;

fn config() exec.Options {
    return .{ .verbose = root.verbose, .trace = root.trace };
}

fn executeCase(tc: exec.Case) !void {
    try exec.execute(gpa, tc, .pikevm, config());
}

test "fowler/basic/basic3" {
    try executeCase(.{
        .name = "fowler/basic/basic3",
        .pattern = "abracadabra$",
        .input = .{ .haystack = "abracadabracadabra", .anchored = false },
        .expected = &[_]?Match{.{ .start = 7, .end = 18 }},
        .requires = caps.requires(.{ .anchor_line_end = true }),
    });
}

test "fowler/basic/basic4" {
    try executeCase(.{
        .name = "fowler/basic/basic4",
        .pattern = "a...b",
        .input = .{ .haystack = "abababbb", .anchored = false },
        .expected = &[_]?Match{.{ .start = 2, .end = 7 }},
        .requires = caps.requires(.{ .dot = true }),
    });
}

test "fowler/basic/basic5" {
    try executeCase(.{
        .name = "fowler/basic/basic5",
        .pattern = "XXXXXX",
        .input = .{ .haystack = "..XXXXXX", .anchored = false },
        .expected = &[_]?Match{.{ .start = 2, .end = 8 }},
    });
}

test "fowler/basic/basic6" {
    try executeCase(.{
        .name = "fowler/basic/basic6",
        .pattern = "\\)",
        .input = .{ .haystack = "()", .anchored = false },
        .expected = &[_]?Match{.{ .start = 1, .end = 2 }},
    });
}

test "fowler/basic/basic7" {
    try executeCase(.{
        .name = "fowler/basic/basic7",
        .pattern = "a]",
        .input = .{ .haystack = "a]a", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 2 }},
        .requires = caps.requires(.{ .input_anchored = true }),
    });
}

test "fowler/basic/basic9" {
    try executeCase(.{
        .name = "fowler/basic/basic9",
        .pattern = "\\}",
        .input = .{ .haystack = "}", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 1 }},
        .requires = caps.requires(.{ .input_anchored = true }),
    });
}

test "fowler/basic/basic10" {
    try executeCase(.{
        .name = "fowler/basic/basic10",
        .pattern = "\\]",
        .input = .{ .haystack = "]", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 1 }},
        .requires = caps.requires(.{ .input_anchored = true }),
    });
}

test "fowler/basic/basic12" {
    try executeCase(.{
        .name = "fowler/basic/basic12",
        .pattern = "]",
        .input = .{ .haystack = "]", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 1 }},
        .requires = caps.requires(.{ .input_anchored = true }),
    });
}

test "fowler/basic/basic15" {
    try executeCase(.{
        .name = "fowler/basic/basic15",
        .pattern = "^a",
        .input = .{ .haystack = "ax", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 1 }},
        .requires = caps.requires(.{ .anchor_line_start = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic16" {
    try executeCase(.{
        .name = "fowler/basic/basic16",
        .pattern = "\\^a",
        .input = .{ .haystack = "a^a", .anchored = false },
        .expected = &[_]?Match{.{ .start = 1, .end = 3 }},
    });
}

test "fowler/basic/basic17" {
    try executeCase(.{
        .name = "fowler/basic/basic17",
        .pattern = "a\\^",
        .input = .{ .haystack = "a^", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 2 }},
        .requires = caps.requires(.{ .input_anchored = true }),
    });
}

test "fowler/basic/basic18" {
    try executeCase(.{
        .name = "fowler/basic/basic18",
        .pattern = "a$",
        .input = .{ .haystack = "aa", .anchored = false },
        .expected = &[_]?Match{.{ .start = 1, .end = 2 }},
        .requires = caps.requires(.{ .anchor_line_end = true }),
    });
}

test "fowler/basic/basic19" {
    try executeCase(.{
        .name = "fowler/basic/basic19",
        .pattern = "a\\$",
        .input = .{ .haystack = "a$", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 2 }},
        .requires = caps.requires(.{ .input_anchored = true }),
    });
}

test "fowler/basic/basic20" {
    try executeCase(.{
        .name = "fowler/basic/basic20",
        .pattern = "^$",
        .input = .{ .haystack = "", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 0 }},
        .requires = caps.requires(.{ .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic21" {
    try executeCase(.{
        .name = "fowler/basic/basic21",
        .pattern = "$^",
        .input = .{ .haystack = "", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 0 }},
        .requires = caps.requires(.{ .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic22" {
    try executeCase(.{
        .name = "fowler/basic/basic22",
        .pattern = "a($)",
        .input = .{ .haystack = "aa", .anchored = false },
        .expected = &[_]?Match{
            .{ .start = 1, .end = 2 },
            .{ .start = 2, .end = 2 },
        },
        .requires = caps.requires(.{ .anchor_line_end = true }),
    });
}

test "fowler/basic/basic23" {
    try executeCase(.{
        .name = "fowler/basic/basic23",
        .pattern = "a*(^a)",
        .input = .{ .haystack = "aa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .anchor_line_start = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic24" {
    try executeCase(.{
        .name = "fowler/basic/basic24",
        .pattern = "(..)*(...)*",
        .input = .{ .haystack = "a", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            null,
            null,
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic25" {
    try executeCase(.{
        .name = "fowler/basic/basic25",
        .pattern = "(..)*(...)*",
        .input = .{ .haystack = "abcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 2, .end = 4 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic26" {
    try executeCase(.{
        .name = "fowler/basic/basic26",
        .pattern = "(ab|a)(bc|c)",
        .input = .{ .haystack = "abc", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            .{ .start = 0, .end = 2 },
            .{ .start = 2, .end = 3 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic27" {
    try executeCase(.{
        .name = "fowler/basic/basic27",
        .pattern = "(ab)c|abc",
        .input = .{ .haystack = "abc", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            .{ .start = 0, .end = 2 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic28" {
    try executeCase(.{
        .name = "fowler/basic/basic28",
        .pattern = "a{0}b",
        .input = .{ .haystack = "ab", .anchored = false },
        .expected = &[_]?Match{.{ .start = 1, .end = 2 }},
        .requires = caps.requires(.{ .rep_exact = true }),
    });
}

test "fowler/basic/basic29" {
    try executeCase(.{
        .name = "fowler/basic/basic29",
        .pattern = "(a*)(b?)(b+)b{3}",
        .input = .{ .haystack = "aaabbbbbbb", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 10 },
            .{ .start = 0, .end = 3 },
            .{ .start = 3, .end = 4 },
            .{ .start = 4, .end = 7 },
        },
        .requires = caps.requires(.{ .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .rep_exact = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic30" {
    try executeCase(.{
        .name = "fowler/basic/basic30",
        .pattern = "(a*)(b{0,1})(b{1,})b{3}",
        .input = .{ .haystack = "aaabbbbbbb", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 10 },
            .{ .start = 0, .end = 3 },
            .{ .start = 3, .end = 4 },
            .{ .start = 4, .end = 7 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_exact = true, .rep_min = true, .rep_range = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic32" {
    try executeCase(.{
        .name = "fowler/basic/basic32",
        .pattern = "((a|a)|a)",
        .input = .{ .haystack = "a", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic33" {
    try executeCase(.{
        .name = "fowler/basic/basic33",
        .pattern = "(a*)(a|aa)",
        .input = .{ .haystack = "aaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 0, .end = 3 },
            .{ .start = 3, .end = 4 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic34" {
    try executeCase(.{
        .name = "fowler/basic/basic34",
        .pattern = "a*(a.|aa)",
        .input = .{ .haystack = "aaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 2, .end = 4 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic35" {
    try executeCase(.{
        .name = "fowler/basic/basic35",
        .pattern = "a(b)|c(d)|a(e)f",
        .input = .{ .haystack = "aef", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            null,
            null,
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic36" {
    try executeCase(.{
        .name = "fowler/basic/basic36",
        .pattern = "(a|b)?.*",
        .input = .{ .haystack = "b", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic37" {
    try executeCase(.{
        .name = "fowler/basic/basic37",
        .pattern = "(a|b)c|a(b|c)",
        .input = .{ .haystack = "ac", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 1 },
            null,
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic38" {
    try executeCase(.{
        .name = "fowler/basic/basic38",
        .pattern = "(a|b)c|a(b|c)",
        .input = .{ .haystack = "ab", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            null,
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic39" {
    try executeCase(.{
        .name = "fowler/basic/basic39",
        .pattern = "(a|b)*c|(a|ab)*c",
        .input = .{ .haystack = "abc", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            .{ .start = 1, .end = 2 },
            null,
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic40" {
    try executeCase(.{
        .name = "fowler/basic/basic40",
        .pattern = "(a|b)*c|(a|ab)*c",
        .input = .{ .haystack = "xc", .anchored = false },
        .expected = &[_]?Match{
            .{ .start = 1, .end = 2 },
            null,
            null,
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true }),
    });
}

test "fowler/basic/basic41" {
    try executeCase(.{
        .name = "fowler/basic/basic41",
        .pattern = "(.a|.b).*|.*(.a|.b)",
        .input = .{ .haystack = "xa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic42" {
    try executeCase(.{
        .name = "fowler/basic/basic42",
        .pattern = "a?(ab|ba)ab",
        .input = .{ .haystack = "abab", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 0, .end = 2 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_one = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic43" {
    try executeCase(.{
        .name = "fowler/basic/basic43",
        .pattern = "a?(ac{0}b|ba)ab",
        .input = .{ .haystack = "abab", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 0, .end = 2 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_one = true, .rep_exact = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic44" {
    try executeCase(.{
        .name = "fowler/basic/basic44",
        .pattern = "ab|abab",
        .input = .{ .haystack = "abbabab", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 2 }},
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic45" {
    try executeCase(.{
        .name = "fowler/basic/basic45",
        .pattern = "aba|bab|bba",
        .input = .{ .haystack = "baaabbbaba", .anchored = false },
        .expected = &[_]?Match{.{ .start = 5, .end = 8 }},
        .requires = caps.requires(.{ .alternation = true }),
    });
}

test "fowler/basic/basic46" {
    try executeCase(.{
        .name = "fowler/basic/basic46",
        .pattern = "aba|bab",
        .input = .{ .haystack = "baaabbbaba", .anchored = false },
        .expected = &[_]?Match{.{ .start = 6, .end = 9 }},
        .requires = caps.requires(.{ .alternation = true }),
    });
}

test "fowler/basic/basic47" {
    try executeCase(.{
        .name = "fowler/basic/basic47",
        .pattern = "(aa|aaa)*|(a|aaaaa)",
        .input = .{ .haystack = "aa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            null,
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic48" {
    try executeCase(.{
        .name = "fowler/basic/basic48",
        .pattern = "(a.|.a.)*|(a|.a...)",
        .input = .{ .haystack = "aa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic49" {
    try executeCase(.{
        .name = "fowler/basic/basic49",
        .pattern = "ab|a",
        .input = .{ .haystack = "xabc", .anchored = false },
        .expected = &[_]?Match{.{ .start = 1, .end = 3 }},
        .requires = caps.requires(.{ .alternation = true }),
    });
}

test "fowler/basic/basic50" {
    try executeCase(.{
        .name = "fowler/basic/basic50",
        .pattern = "ab|a",
        .input = .{ .haystack = "xxabc", .anchored = false },
        .expected = &[_]?Match{.{ .start = 2, .end = 4 }},
        .requires = caps.requires(.{ .alternation = true }),
    });
}

test "fowler/basic/basic51" {
    try executeCase(.{
        .name = "fowler/basic/basic51",
        .pattern = "(Ab|cD)*",
        .input = .{ .haystack = "aBcD", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 2, .end = 4 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .ignore_case = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic52" {
    try executeCase(.{
        .name = "fowler/basic/basic52",
        .pattern = "[^-]",
        .input = .{ .haystack = "--a", .anchored = false },
        .expected = &[_]?Match{.{ .start = 2, .end = 3 }},
        .requires = caps.requires(.{ .class_simple = true, .class_negated = true }),
    });
}

test "fowler/basic/basic53" {
    try executeCase(.{
        .name = "fowler/basic/basic53",
        .pattern = "[a-]*",
        .input = .{ .haystack = "--a", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 3 }},
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic54" {
    try executeCase(.{
        .name = "fowler/basic/basic54",
        .pattern = "[a-m-]*",
        .input = .{ .haystack = "--amoma--", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 4 }},
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .class_range = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic55" {
    try executeCase(.{
        .name = "fowler/basic/basic55",
        .pattern = ":::1:::0:|:::1:1:0:",
        .input = .{ .haystack = ":::0:::1:::1:::0:", .anchored = false },
        .expected = &[_]?Match{.{ .start = 8, .end = 17 }},
        .requires = caps.requires(.{ .alternation = true }),
    });
}

test "fowler/basic/basic56" {
    try executeCase(.{
        .name = "fowler/basic/basic56",
        .pattern = ":::1:::0:|:::1:1:1:",
        .input = .{ .haystack = ":::0:::1:::1:::0:", .anchored = false },
        .expected = &[_]?Match{.{ .start = 8, .end = 17 }},
        .requires = caps.requires(.{ .alternation = true }),
    });
}

test "fowler/basic/basic57" {
    try executeCase(.{
        .name = "fowler/basic/basic57",
        .pattern = "[[:upper:]]",
        .input = .{ .haystack = "A", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 1 }},
        .requires = caps.requires(.{ .class_simple = true, .class_posix = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic58" {
    try executeCase(.{
        .name = "fowler/basic/basic58",
        .pattern = "[[:lower:]]+",
        .input = .{ .haystack = "`az{", .anchored = false },
        .expected = &[_]?Match{.{ .start = 1, .end = 3 }},
        .requires = caps.requires(.{ .rep_one_or_more = true, .class_simple = true, .class_posix = true }),
    });
}

test "fowler/basic/basic59" {
    try executeCase(.{
        .name = "fowler/basic/basic59",
        .pattern = "[[:upper:]]+",
        .input = .{ .haystack = "@AZ[", .anchored = false },
        .expected = &[_]?Match{.{ .start = 1, .end = 3 }},
        .requires = caps.requires(.{ .rep_one_or_more = true, .class_simple = true, .class_posix = true }),
    });
}

test "fowler/basic/basic65" {
    try executeCase(.{
        .name = "fowler/basic/basic65",
        .pattern = "\\n",
        .input = .{ .haystack = "\\n", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 1 }},
        .requires = caps.requires(.{ .escape_c_style = true, .case_unescape = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic66" {
    try executeCase(.{
        .name = "fowler/basic/basic66",
        .pattern = "\\n",
        .input = .{ .haystack = "\\n", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 1 }},
        .requires = caps.requires(.{ .escape_c_style = true, .case_unescape = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic67" {
    try executeCase(.{
        .name = "fowler/basic/basic67",
        .pattern = "[^a]",
        .input = .{ .haystack = "\\n", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 1 }},
        .requires = caps.requires(.{ .class_simple = true, .class_negated = true, .case_unescape = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic68" {
    try executeCase(.{
        .name = "fowler/basic/basic68",
        .pattern = "\\na",
        .input = .{ .haystack = "\\na", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 2 }},
        .requires = caps.requires(.{ .escape_c_style = true, .case_unescape = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic69" {
    try executeCase(.{
        .name = "fowler/basic/basic69",
        .pattern = "(a)(b)(c)",
        .input = .{ .haystack = "abc", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            .{ .start = 0, .end = 1 },
            .{ .start = 1, .end = 2 },
            .{ .start = 2, .end = 3 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    });
}

test "fowler/basic/basic70" {
    try executeCase(.{
        .name = "fowler/basic/basic70",
        .pattern = "xxx",
        .input = .{ .haystack = "xxx", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 3 }},
        .requires = caps.requires(.{ .input_anchored = true }),
    });
}

test "fowler/basic/basic72" {
    try executeCase(.{
        .name = "fowler/basic/basic72",
        .pattern = "(?:^|[ (,;])(?:(?:(?:[Ff]eb[^ ]* *|0*2/|\\* */?)0*[6-7]))(?:[^0-9]|$)",
        .input = .{ .haystack = "feb 6,", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 6 }},
        .requires = caps.requires(.{ .alternation = true, .noncapture_group = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .class_simple = true, .class_range = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic74" {
    try executeCase(.{
        .name = "fowler/basic/basic74",
        .pattern = "(?:^|[ (,;])(?:(?:(?:[Ff]eb[^ ]* *|0*2/|\\* */?)0*[6-7]))(?:[^0-9]|$)",
        .input = .{ .haystack = "2/7", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 3 }},
        .requires = caps.requires(.{ .alternation = true, .noncapture_group = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .class_simple = true, .class_range = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic76" {
    try executeCase(.{
        .name = "fowler/basic/basic76",
        .pattern = "(?:^|[ (,;])(?:(?:(?:[Ff]eb[^ ]* *|0*2/|\\* */?)0*[6-7]))(?:[^0-9]|$)",
        .input = .{ .haystack = "feb 1,Feb 6", .anchored = false },
        .expected = &[_]?Match{.{ .start = 5, .end = 11 }},
        .requires = caps.requires(.{ .alternation = true, .noncapture_group = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .class_simple = true, .class_range = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true }),
    });
}

test "fowler/basic/basic78" {
    try executeCase(.{
        .name = "fowler/basic/basic78",
        .pattern = "(((?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:x))))))))))))))))))))))))))))))",
        .input = .{ .haystack = "x", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .noncapture_group = true, .rep_zero_or_one = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic80" {
    try executeCase(.{
        .name = "fowler/basic/basic80",
        .pattern = "(((?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:x))))))))))))))))))))))))))))))*",
        .input = .{ .haystack = "xx", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 1, .end = 2 },
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .noncapture_group = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic81" {
    try executeCase(.{
        .name = "fowler/basic/basic81",
        .pattern = "a?(ab|ba)*",
        .input = .{ .haystack = "ababababababababababababababababababababababababababababababababababababababababa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 81 },
            .{ .start = 79, .end = 81 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic82" {
    try executeCase(.{
        .name = "fowler/basic/basic82",
        .pattern = "abaa|abbaa|abbbaa|abbbbaa",
        .input = .{ .haystack = "ababbabbbabbbabbbbabbbbaa", .anchored = false },
        .expected = &[_]?Match{.{ .start = 18, .end = 25 }},
        .requires = caps.requires(.{ .alternation = true }),
    });
}

test "fowler/basic/basic83" {
    try executeCase(.{
        .name = "fowler/basic/basic83",
        .pattern = "abaa|abbaa|abbbaa|abbbbaa",
        .input = .{ .haystack = "ababbabbbabbbabbbbabaa", .anchored = false },
        .expected = &[_]?Match{.{ .start = 18, .end = 22 }},
        .requires = caps.requires(.{ .alternation = true }),
    });
}

test "fowler/basic/basic84" {
    try executeCase(.{
        .name = "fowler/basic/basic84",
        .pattern = "aaac|aabc|abac|abbc|baac|babc|bbac|bbbc",
        .input = .{ .haystack = "baaabbbabac", .anchored = false },
        .expected = &[_]?Match{.{ .start = 7, .end = 11 }},
        .requires = caps.requires(.{ .alternation = true }),
    });
}

test "fowler/basic/basic86" {
    try executeCase(.{
        .name = "fowler/basic/basic86",
        .pattern = ".*",
        .input = .{ .haystack = "\\x01\\x7f", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 2 }},
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_more = true, .case_unescape = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic87" {
    try executeCase(.{
        .name = "fowler/basic/basic87",
        .pattern = "aaaa|bbbb|cccc|ddddd|eeeeee|fffffff|gggg|hhhh|iiiii|jjjjj|kkkkk|llll",
        .input = .{ .haystack = "XaaaXbbbXcccXdddXeeeXfffXgggXhhhXiiiXjjjXkkkXlllXcbaXaaaa", .anchored = false },
        .expected = &[_]?Match{.{ .start = 53, .end = 57 }},
        .requires = caps.requires(.{ .alternation = true }),
    });
}

test "fowler/basic/basic89" {
    try executeCase(.{
        .name = "fowler/basic/basic89",
        .pattern = "a*a*a*a*a*b",
        .input = .{ .haystack = "aaaaaaaaab", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 10 }},
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic90" {
    try executeCase(.{
        .name = "fowler/basic/basic90",
        .pattern = "^",
        .input = .{ .haystack = "", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 0 }},
        .requires = caps.requires(.{ .anchor_line_start = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic91" {
    try executeCase(.{
        .name = "fowler/basic/basic91",
        .pattern = "$",
        .input = .{ .haystack = "", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 0 }},
        .requires = caps.requires(.{ .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic92" {
    try executeCase(.{
        .name = "fowler/basic/basic92",
        .pattern = "^$",
        .input = .{ .haystack = "", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 0 }},
        .requires = caps.requires(.{ .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic93" {
    try executeCase(.{
        .name = "fowler/basic/basic93",
        .pattern = "^a$",
        .input = .{ .haystack = "a", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 1 }},
        .requires = caps.requires(.{ .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic94" {
    try executeCase(.{
        .name = "fowler/basic/basic94",
        .pattern = "abc",
        .input = .{ .haystack = "abc", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 3 }},
        .requires = caps.requires(.{ .input_anchored = true }),
    });
}

test "fowler/basic/basic95" {
    try executeCase(.{
        .name = "fowler/basic/basic95",
        .pattern = "abc",
        .input = .{ .haystack = "xabcy", .anchored = false },
        .expected = &[_]?Match{.{ .start = 1, .end = 4 }},
    });
}

test "fowler/basic/basic96" {
    try executeCase(.{
        .name = "fowler/basic/basic96",
        .pattern = "abc",
        .input = .{ .haystack = "ababc", .anchored = false },
        .expected = &[_]?Match{.{ .start = 2, .end = 5 }},
    });
}

test "fowler/basic/basic97" {
    try executeCase(.{
        .name = "fowler/basic/basic97",
        .pattern = "ab*c",
        .input = .{ .haystack = "abc", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 3 }},
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic98" {
    try executeCase(.{
        .name = "fowler/basic/basic98",
        .pattern = "ab*bc",
        .input = .{ .haystack = "abc", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 3 }},
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic99" {
    try executeCase(.{
        .name = "fowler/basic/basic99",
        .pattern = "ab*bc",
        .input = .{ .haystack = "abbc", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 4 }},
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic100" {
    try executeCase(.{
        .name = "fowler/basic/basic100",
        .pattern = "ab*bc",
        .input = .{ .haystack = "abbbbc", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 6 }},
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic101" {
    try executeCase(.{
        .name = "fowler/basic/basic101",
        .pattern = "ab+bc",
        .input = .{ .haystack = "abbc", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 4 }},
        .requires = caps.requires(.{ .rep_one_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic102" {
    try executeCase(.{
        .name = "fowler/basic/basic102",
        .pattern = "ab+bc",
        .input = .{ .haystack = "abbbbc", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 6 }},
        .requires = caps.requires(.{ .rep_one_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic103" {
    try executeCase(.{
        .name = "fowler/basic/basic103",
        .pattern = "ab?bc",
        .input = .{ .haystack = "abbc", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 4 }},
        .requires = caps.requires(.{ .rep_zero_or_one = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic104" {
    try executeCase(.{
        .name = "fowler/basic/basic104",
        .pattern = "ab?bc",
        .input = .{ .haystack = "abc", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 3 }},
        .requires = caps.requires(.{ .rep_zero_or_one = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic105" {
    try executeCase(.{
        .name = "fowler/basic/basic105",
        .pattern = "ab?c",
        .input = .{ .haystack = "abc", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 3 }},
        .requires = caps.requires(.{ .rep_zero_or_one = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic106" {
    try executeCase(.{
        .name = "fowler/basic/basic106",
        .pattern = "^abc$",
        .input = .{ .haystack = "abc", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 3 }},
        .requires = caps.requires(.{ .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic107" {
    try executeCase(.{
        .name = "fowler/basic/basic107",
        .pattern = "^abc",
        .input = .{ .haystack = "abcc", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 3 }},
        .requires = caps.requires(.{ .anchor_line_start = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic108" {
    try executeCase(.{
        .name = "fowler/basic/basic108",
        .pattern = "abc$",
        .input = .{ .haystack = "aabc", .anchored = false },
        .expected = &[_]?Match{.{ .start = 1, .end = 4 }},
        .requires = caps.requires(.{ .anchor_line_end = true }),
    });
}

test "fowler/basic/basic109" {
    try executeCase(.{
        .name = "fowler/basic/basic109",
        .pattern = "^",
        .input = .{ .haystack = "abc", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 0 }},
        .requires = caps.requires(.{ .anchor_line_start = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic110" {
    try executeCase(.{
        .name = "fowler/basic/basic110",
        .pattern = "$",
        .input = .{ .haystack = "abc", .anchored = false },
        .expected = &[_]?Match{.{ .start = 3, .end = 3 }},
        .requires = caps.requires(.{ .anchor_line_end = true }),
    });
}

test "fowler/basic/basic111" {
    try executeCase(.{
        .name = "fowler/basic/basic111",
        .pattern = "a.c",
        .input = .{ .haystack = "abc", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 3 }},
        .requires = caps.requires(.{ .dot = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic112" {
    try executeCase(.{
        .name = "fowler/basic/basic112",
        .pattern = "a.c",
        .input = .{ .haystack = "axc", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 3 }},
        .requires = caps.requires(.{ .dot = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic113" {
    try executeCase(.{
        .name = "fowler/basic/basic113",
        .pattern = "a.*c",
        .input = .{ .haystack = "axyzc", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 5 }},
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic114" {
    try executeCase(.{
        .name = "fowler/basic/basic114",
        .pattern = "a[bc]d",
        .input = .{ .haystack = "abd", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 3 }},
        .requires = caps.requires(.{ .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic115" {
    try executeCase(.{
        .name = "fowler/basic/basic115",
        .pattern = "a[b-d]e",
        .input = .{ .haystack = "ace", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 3 }},
        .requires = caps.requires(.{ .class_simple = true, .class_range = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic116" {
    try executeCase(.{
        .name = "fowler/basic/basic116",
        .pattern = "a[b-d]",
        .input = .{ .haystack = "aac", .anchored = false },
        .expected = &[_]?Match{.{ .start = 1, .end = 3 }},
        .requires = caps.requires(.{ .class_simple = true, .class_range = true }),
    });
}

test "fowler/basic/basic117" {
    try executeCase(.{
        .name = "fowler/basic/basic117",
        .pattern = "a[-b]",
        .input = .{ .haystack = "a-", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 2 }},
        .requires = caps.requires(.{ .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic118" {
    try executeCase(.{
        .name = "fowler/basic/basic118",
        .pattern = "a[b-]",
        .input = .{ .haystack = "a-", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 2 }},
        .requires = caps.requires(.{ .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic119" {
    try executeCase(.{
        .name = "fowler/basic/basic119",
        .pattern = "a]",
        .input = .{ .haystack = "a]", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 2 }},
        .requires = caps.requires(.{ .input_anchored = true }),
    });
}

test "fowler/basic/basic120" {
    try executeCase(.{
        .name = "fowler/basic/basic120",
        .pattern = "a[]]b",
        .input = .{ .haystack = "a]b", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 3 }},
        .requires = caps.requires(.{ .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic121" {
    try executeCase(.{
        .name = "fowler/basic/basic121",
        .pattern = "a[^bc]d",
        .input = .{ .haystack = "aed", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 3 }},
        .requires = caps.requires(.{ .class_simple = true, .class_negated = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic122" {
    try executeCase(.{
        .name = "fowler/basic/basic122",
        .pattern = "a[^-b]c",
        .input = .{ .haystack = "adc", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 3 }},
        .requires = caps.requires(.{ .class_simple = true, .class_negated = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic123" {
    try executeCase(.{
        .name = "fowler/basic/basic123",
        .pattern = "a[^]b]c",
        .input = .{ .haystack = "adc", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 3 }},
        .requires = caps.requires(.{ .class_simple = true, .class_negated = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic124" {
    try executeCase(.{
        .name = "fowler/basic/basic124",
        .pattern = "ab|cd",
        .input = .{ .haystack = "abc", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 2 }},
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic125" {
    try executeCase(.{
        .name = "fowler/basic/basic125",
        .pattern = "ab|cd",
        .input = .{ .haystack = "abcd", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 2 }},
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic126" {
    try executeCase(.{
        .name = "fowler/basic/basic126",
        .pattern = "a\\(b",
        .input = .{ .haystack = "a(b", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 3 }},
        .requires = caps.requires(.{ .input_anchored = true }),
    });
}

test "fowler/basic/basic127" {
    try executeCase(.{
        .name = "fowler/basic/basic127",
        .pattern = "a\\(*b",
        .input = .{ .haystack = "ab", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 2 }},
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic128" {
    try executeCase(.{
        .name = "fowler/basic/basic128",
        .pattern = "a\\(*b",
        .input = .{ .haystack = "a((b", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 4 }},
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic129" {
    try executeCase(.{
        .name = "fowler/basic/basic129",
        .pattern = "((a))",
        .input = .{ .haystack = "abc", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    });
}

test "fowler/basic/basic130" {
    try executeCase(.{
        .name = "fowler/basic/basic130",
        .pattern = "(a)b(c)",
        .input = .{ .haystack = "abc", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            .{ .start = 0, .end = 1 },
            .{ .start = 2, .end = 3 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    });
}

test "fowler/basic/basic131" {
    try executeCase(.{
        .name = "fowler/basic/basic131",
        .pattern = "a+b+c",
        .input = .{ .haystack = "aabbabc", .anchored = false },
        .expected = &[_]?Match{.{ .start = 4, .end = 7 }},
        .requires = caps.requires(.{ .rep_one_or_more = true }),
    });
}

test "fowler/basic/basic132" {
    try executeCase(.{
        .name = "fowler/basic/basic132",
        .pattern = "a*",
        .input = .{ .haystack = "aaa", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 3 }},
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic133" {
    try executeCase(.{
        .name = "fowler/basic/basic133",
        .pattern = "(a*)*",
        .input = .{ .haystack = "-", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic134" {
    try executeCase(.{
        .name = "fowler/basic/basic134",
        .pattern = "(a*)+",
        .input = .{ .haystack = "-", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic135" {
    try executeCase(.{
        .name = "fowler/basic/basic135",
        .pattern = "(a*|b)*",
        .input = .{ .haystack = "-", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic136" {
    try executeCase(.{
        .name = "fowler/basic/basic136",
        .pattern = "(a+|b)*",
        .input = .{ .haystack = "ab", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic137" {
    try executeCase(.{
        .name = "fowler/basic/basic137",
        .pattern = "(a+|b)+",
        .input = .{ .haystack = "ab", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_one_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic138" {
    try executeCase(.{
        .name = "fowler/basic/basic138",
        .pattern = "(a+|b)?",
        .input = .{ .haystack = "ab", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_one = true, .rep_one_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic139" {
    try executeCase(.{
        .name = "fowler/basic/basic139",
        .pattern = "[^ab]*",
        .input = .{ .haystack = "cde", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 3 }},
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .class_negated = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic140" {
    try executeCase(.{
        .name = "fowler/basic/basic140",
        .pattern = "(^)*",
        .input = .{ .haystack = "-", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .anchor_line_start = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic141" {
    try executeCase(.{
        .name = "fowler/basic/basic141",
        .pattern = "a*",
        .input = .{ .haystack = "", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 0 }},
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic142" {
    try executeCase(.{
        .name = "fowler/basic/basic142",
        .pattern = "([abc])*d",
        .input = .{ .haystack = "abbbcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 4, .end = 5 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic143" {
    try executeCase(.{
        .name = "fowler/basic/basic143",
        .pattern = "([abc])*bcd",
        .input = .{ .haystack = "abcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic144" {
    try executeCase(.{
        .name = "fowler/basic/basic144",
        .pattern = "a|b|c|d|e",
        .input = .{ .haystack = "e", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 1 }},
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic145" {
    try executeCase(.{
        .name = "fowler/basic/basic145",
        .pattern = "(a|b|c|d|e)f",
        .input = .{ .haystack = "ef", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic146" {
    try executeCase(.{
        .name = "fowler/basic/basic146",
        .pattern = "((a*|b))*",
        .input = .{ .haystack = "-", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic147" {
    try executeCase(.{
        .name = "fowler/basic/basic147",
        .pattern = "abcd*efg",
        .input = .{ .haystack = "abcdefg", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 7 }},
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic148" {
    try executeCase(.{
        .name = "fowler/basic/basic148",
        .pattern = "ab*",
        .input = .{ .haystack = "xabyabbbz", .anchored = false },
        .expected = &[_]?Match{.{ .start = 1, .end = 3 }},
        .requires = caps.requires(.{ .rep_zero_or_more = true }),
    });
}

test "fowler/basic/basic149" {
    try executeCase(.{
        .name = "fowler/basic/basic149",
        .pattern = "ab*",
        .input = .{ .haystack = "xayabbbz", .anchored = false },
        .expected = &[_]?Match{.{ .start = 1, .end = 2 }},
        .requires = caps.requires(.{ .rep_zero_or_more = true }),
    });
}

test "fowler/basic/basic150" {
    try executeCase(.{
        .name = "fowler/basic/basic150",
        .pattern = "(ab|cd)e",
        .input = .{ .haystack = "abcde", .anchored = false },
        .expected = &[_]?Match{
            .{ .start = 2, .end = 5 },
            .{ .start = 2, .end = 4 },
        },
        .requires = caps.requires(.{ .alternation = true }),
    });
}

test "fowler/basic/basic151" {
    try executeCase(.{
        .name = "fowler/basic/basic151",
        .pattern = "[abhgefdc]ij",
        .input = .{ .haystack = "hij", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 3 }},
        .requires = caps.requires(.{ .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic152" {
    try executeCase(.{
        .name = "fowler/basic/basic152",
        .pattern = "(a|b)c*d",
        .input = .{ .haystack = "abcd", .anchored = false },
        .expected = &[_]?Match{
            .{ .start = 1, .end = 4 },
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true }),
    });
}

test "fowler/basic/basic153" {
    try executeCase(.{
        .name = "fowler/basic/basic153",
        .pattern = "(ab|ab*)bc",
        .input = .{ .haystack = "abc", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic154" {
    try executeCase(.{
        .name = "fowler/basic/basic154",
        .pattern = "a([bc]*)c*",
        .input = .{ .haystack = "abc", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            .{ .start = 1, .end = 3 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic155" {
    try executeCase(.{
        .name = "fowler/basic/basic155",
        .pattern = "a([bc]*)(c*d)",
        .input = .{ .haystack = "abcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 1, .end = 3 },
            .{ .start = 3, .end = 4 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic156" {
    try executeCase(.{
        .name = "fowler/basic/basic156",
        .pattern = "a([bc]+)(c*d)",
        .input = .{ .haystack = "abcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 1, .end = 3 },
            .{ .start = 3, .end = 4 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic157" {
    try executeCase(.{
        .name = "fowler/basic/basic157",
        .pattern = "a([bc]*)(c+d)",
        .input = .{ .haystack = "abcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 1, .end = 2 },
            .{ .start = 2, .end = 4 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic158" {
    try executeCase(.{
        .name = "fowler/basic/basic158",
        .pattern = "a[bcd]*dcdcde",
        .input = .{ .haystack = "adcdcde", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 7 }},
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic159" {
    try executeCase(.{
        .name = "fowler/basic/basic159",
        .pattern = "(ab|a)b*c",
        .input = .{ .haystack = "abc", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            .{ .start = 0, .end = 2 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic160" {
    try executeCase(.{
        .name = "fowler/basic/basic160",
        .pattern = "((a)(b)c)(d)",
        .input = .{ .haystack = "abcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 0, .end = 3 },
            .{ .start = 0, .end = 1 },
            .{ .start = 1, .end = 2 },
            .{ .start = 3, .end = 4 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    });
}

test "fowler/basic/basic161" {
    try executeCase(.{
        .name = "fowler/basic/basic161",
        .pattern = "[A-Za-z_][A-Za-z0-9_]*",
        .input = .{ .haystack = "alpha", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 5 }},
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .class_range = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic162" {
    try executeCase(.{
        .name = "fowler/basic/basic162",
        .pattern = "^a(bc+|b[eh])g|.h$",
        .input = .{ .haystack = "abh", .anchored = false },
        .expected = &[_]?Match{
            .{ .start = 1, .end = 3 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_one_or_more = true, .class_simple = true, .anchor_line_start = true, .anchor_line_end = true }),
    });
}

test "fowler/basic/basic163" {
    try executeCase(.{
        .name = "fowler/basic/basic163",
        .pattern = "(bc+d$|ef*g.|h?i(j|k))",
        .input = .{ .haystack = "effgz", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 5 },
            .{ .start = 0, .end = 5 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic164" {
    try executeCase(.{
        .name = "fowler/basic/basic164",
        .pattern = "(bc+d$|ef*g.|h?i(j|k))",
        .input = .{ .haystack = "ij", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic165" {
    try executeCase(.{
        .name = "fowler/basic/basic165",
        .pattern = "(bc+d$|ef*g.|h?i(j|k))",
        .input = .{ .haystack = "reffgz", .anchored = false },
        .expected = &[_]?Match{
            .{ .start = 1, .end = 6 },
            .{ .start = 1, .end = 6 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .anchor_line_end = true }),
    });
}

test "fowler/basic/basic166" {
    try executeCase(.{
        .name = "fowler/basic/basic166",
        .pattern = "(((((((((a)))))))))",
        .input = .{ .haystack = "a", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    });
}

test "fowler/basic/basic167" {
    try executeCase(.{
        .name = "fowler/basic/basic167",
        .pattern = "multiple words",
        .input = .{ .haystack = "multiple words yeah", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 14 }},
        .requires = caps.requires(.{ .input_anchored = true }),
    });
}

test "fowler/basic/basic168" {
    try executeCase(.{
        .name = "fowler/basic/basic168",
        .pattern = "(.*)c(.*)",
        .input = .{ .haystack = "abcde", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 5 },
            .{ .start = 0, .end = 2 },
            .{ .start = 3, .end = 5 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic169" {
    try executeCase(.{
        .name = "fowler/basic/basic169",
        .pattern = "abcd",
        .input = .{ .haystack = "abcd", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 4 }},
        .requires = caps.requires(.{ .input_anchored = true }),
    });
}

test "fowler/basic/basic170" {
    try executeCase(.{
        .name = "fowler/basic/basic170",
        .pattern = "a(bc)d",
        .input = .{ .haystack = "abcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 1, .end = 3 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    });
}

test "fowler/basic/basic171" {
    try executeCase(.{
        .name = "fowler/basic/basic171",
        .pattern = "a[\\x01-\\x03]?c",
        .input = .{ .haystack = "a\\x02c", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 3 }},
        .requires = caps.requires(.{ .rep_zero_or_one = true, .class_simple = true, .class_range = true, .escape_hex_byte = true, .case_unescape = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic172" {
    try executeCase(.{
        .name = "fowler/basic/basic172",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .input = .{ .haystack = "Muammar Qaddafi", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 15 },
            null,
            .{ .start = 10, .end = 12 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic173" {
    try executeCase(.{
        .name = "fowler/basic/basic173",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .input = .{ .haystack = "Mo'ammar Gadhafi", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 16 },
            null,
            .{ .start = 11, .end = 13 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic174" {
    try executeCase(.{
        .name = "fowler/basic/basic174",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .input = .{ .haystack = "Muammar Kaddafi", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 15 },
            null,
            .{ .start = 10, .end = 12 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic175" {
    try executeCase(.{
        .name = "fowler/basic/basic175",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .input = .{ .haystack = "Muammar Qadhafi", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 15 },
            null,
            .{ .start = 10, .end = 12 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic176" {
    try executeCase(.{
        .name = "fowler/basic/basic176",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .input = .{ .haystack = "Muammar Gadafi", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 14 },
            null,
            .{ .start = 10, .end = 11 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic177" {
    try executeCase(.{
        .name = "fowler/basic/basic177",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .input = .{ .haystack = "Mu'ammar Qadafi", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 15 },
            null,
            .{ .start = 11, .end = 12 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic178" {
    try executeCase(.{
        .name = "fowler/basic/basic178",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .input = .{ .haystack = "Moamar Gaddafi", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 14 },
            null,
            .{ .start = 9, .end = 11 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic179" {
    try executeCase(.{
        .name = "fowler/basic/basic179",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .input = .{ .haystack = "Mu'ammar Qadhdhafi", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 18 },
            null,
            .{ .start = 13, .end = 15 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic180" {
    try executeCase(.{
        .name = "fowler/basic/basic180",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .input = .{ .haystack = "Muammar Khaddafi", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 16 },
            null,
            .{ .start = 11, .end = 13 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic181" {
    try executeCase(.{
        .name = "fowler/basic/basic181",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .input = .{ .haystack = "Muammar Ghaddafy", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 16 },
            null,
            .{ .start = 11, .end = 13 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic182" {
    try executeCase(.{
        .name = "fowler/basic/basic182",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .input = .{ .haystack = "Muammar Ghadafi", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 15 },
            null,
            .{ .start = 11, .end = 12 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic183" {
    try executeCase(.{
        .name = "fowler/basic/basic183",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .input = .{ .haystack = "Muammar Ghaddafi", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 16 },
            null,
            .{ .start = 11, .end = 13 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic184" {
    try executeCase(.{
        .name = "fowler/basic/basic184",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .input = .{ .haystack = "Muamar Kaddafi", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 14 },
            null,
            .{ .start = 9, .end = 11 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic185" {
    try executeCase(.{
        .name = "fowler/basic/basic185",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .input = .{ .haystack = "Muammar Quathafi", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 16 },
            null,
            .{ .start = 11, .end = 13 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic186" {
    try executeCase(.{
        .name = "fowler/basic/basic186",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .input = .{ .haystack = "Muammar Gheddafi", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 16 },
            null,
            .{ .start = 11, .end = 13 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic187" {
    try executeCase(.{
        .name = "fowler/basic/basic187",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .input = .{ .haystack = "Moammar Khadafy", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 15 },
            null,
            .{ .start = 11, .end = 12 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic188" {
    try executeCase(.{
        .name = "fowler/basic/basic188",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .input = .{ .haystack = "Moammar Qudhafi", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 15 },
            null,
            .{ .start = 10, .end = 12 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic189" {
    try executeCase(.{
        .name = "fowler/basic/basic189",
        .pattern = "a+(b|c)*d+",
        .input = .{ .haystack = "aabcdd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 3, .end = 4 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic190" {
    try executeCase(.{
        .name = "fowler/basic/basic190",
        .pattern = "^.+$",
        .input = .{ .haystack = "vivi", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 4 }},
        .requires = caps.requires(.{ .dot = true, .rep_one_or_more = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic191" {
    try executeCase(.{
        .name = "fowler/basic/basic191",
        .pattern = "^(.+)$",
        .input = .{ .haystack = "vivi", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 0, .end = 4 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_one_or_more = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic192" {
    try executeCase(.{
        .name = "fowler/basic/basic192",
        .pattern = "^([^!.]+).att.com!(.+)$",
        .input = .{ .haystack = "gryphon.att.com!eby", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 19 },
            .{ .start = 0, .end = 7 },
            .{ .start = 16, .end = 19 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic193" {
    try executeCase(.{
        .name = "fowler/basic/basic193",
        .pattern = "^([^!]+!)?([^!]+)$",
        .input = .{ .haystack = "bas", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            null,
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .rep_zero_or_one = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic194" {
    try executeCase(.{
        .name = "fowler/basic/basic194",
        .pattern = "^([^!]+!)?([^!]+)$",
        .input = .{ .haystack = "bar!bas", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 4 },
            .{ .start = 4, .end = 7 },
        },
        .requires = caps.requires(.{ .rep_zero_or_one = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic195" {
    try executeCase(.{
        .name = "fowler/basic/basic195",
        .pattern = "^([^!]+!)?([^!]+)$",
        .input = .{ .haystack = "foo!bas", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 4 },
            .{ .start = 4, .end = 7 },
        },
        .requires = caps.requires(.{ .rep_zero_or_one = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic196" {
    try executeCase(.{
        .name = "fowler/basic/basic196",
        .pattern = "^.+!([^!]+!)([^!]+)$",
        .input = .{ .haystack = "foo!bar!bas", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 11 },
            .{ .start = 4, .end = 8 },
            .{ .start = 8, .end = 11 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic197" {
    try executeCase(.{
        .name = "fowler/basic/basic197",
        .pattern = "((foo)|(bar))!bas",
        .input = .{ .haystack = "bar!bas", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 3 },
            null,
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic198" {
    try executeCase(.{
        .name = "fowler/basic/basic198",
        .pattern = "((foo)|(bar))!bas",
        .input = .{ .haystack = "foo!bar!bas", .anchored = false },
        .expected = &[_]?Match{
            .{ .start = 4, .end = 11 },
            .{ .start = 4, .end = 7 },
            null,
            .{ .start = 4, .end = 7 },
        },
        .requires = caps.requires(.{ .alternation = true }),
    });
}

test "fowler/basic/basic199" {
    try executeCase(.{
        .name = "fowler/basic/basic199",
        .pattern = "((foo)|(bar))!bas",
        .input = .{ .haystack = "foo!bas", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 3 },
            .{ .start = 0, .end = 3 },
            null,
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic200" {
    try executeCase(.{
        .name = "fowler/basic/basic200",
        .pattern = "((foo)|bar)!bas",
        .input = .{ .haystack = "bar!bas", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 3 },
            null,
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic201" {
    try executeCase(.{
        .name = "fowler/basic/basic201",
        .pattern = "((foo)|bar)!bas",
        .input = .{ .haystack = "foo!bar!bas", .anchored = false },
        .expected = &[_]?Match{
            .{ .start = 4, .end = 11 },
            .{ .start = 4, .end = 7 },
            null,
        },
        .requires = caps.requires(.{ .alternation = true }),
    });
}

test "fowler/basic/basic202" {
    try executeCase(.{
        .name = "fowler/basic/basic202",
        .pattern = "((foo)|bar)!bas",
        .input = .{ .haystack = "foo!bas", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 3 },
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic203" {
    try executeCase(.{
        .name = "fowler/basic/basic203",
        .pattern = "(foo|(bar))!bas",
        .input = .{ .haystack = "bar!bas", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 3 },
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic204" {
    try executeCase(.{
        .name = "fowler/basic/basic204",
        .pattern = "(foo|(bar))!bas",
        .input = .{ .haystack = "foo!bar!bas", .anchored = false },
        .expected = &[_]?Match{
            .{ .start = 4, .end = 11 },
            .{ .start = 4, .end = 7 },
            .{ .start = 4, .end = 7 },
        },
        .requires = caps.requires(.{ .alternation = true }),
    });
}

test "fowler/basic/basic205" {
    try executeCase(.{
        .name = "fowler/basic/basic205",
        .pattern = "(foo|(bar))!bas",
        .input = .{ .haystack = "foo!bas", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 3 },
            null,
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic206" {
    try executeCase(.{
        .name = "fowler/basic/basic206",
        .pattern = "(foo|bar)!bas",
        .input = .{ .haystack = "bar!bas", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic207" {
    try executeCase(.{
        .name = "fowler/basic/basic207",
        .pattern = "(foo|bar)!bas",
        .input = .{ .haystack = "foo!bar!bas", .anchored = false },
        .expected = &[_]?Match{
            .{ .start = 4, .end = 11 },
            .{ .start = 4, .end = 7 },
        },
        .requires = caps.requires(.{ .alternation = true }),
    });
}

test "fowler/basic/basic208" {
    try executeCase(.{
        .name = "fowler/basic/basic208",
        .pattern = "(foo|bar)!bas",
        .input = .{ .haystack = "foo!bas", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic209" {
    try executeCase(.{
        .name = "fowler/basic/basic209",
        .pattern = "^(([^!]+!)?([^!]+)|.+!([^!]+!)([^!]+))$",
        .input = .{ .haystack = "foo!bar!bas", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 11 },
            .{ .start = 0, .end = 11 },
            null,
            null,
            .{ .start = 4, .end = 8 },
            .{ .start = 8, .end = 11 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic210" {
    try executeCase(.{
        .name = "fowler/basic/basic210",
        .pattern = "^([^!]+!)?([^!]+)$|^.+!([^!]+!)([^!]+)$",
        .input = .{ .haystack = "bas", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            null,
            .{ .start = 0, .end = 3 },
            null,
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic211" {
    try executeCase(.{
        .name = "fowler/basic/basic211",
        .pattern = "^([^!]+!)?([^!]+)$|^.+!([^!]+!)([^!]+)$",
        .input = .{ .haystack = "bar!bas", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 4 },
            .{ .start = 4, .end = 7 },
            null,
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic212" {
    try executeCase(.{
        .name = "fowler/basic/basic212",
        .pattern = "^([^!]+!)?([^!]+)$|^.+!([^!]+!)([^!]+)$",
        .input = .{ .haystack = "foo!bar!bas", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 11 },
            null,
            null,
            .{ .start = 4, .end = 8 },
            .{ .start = 8, .end = 11 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic213" {
    try executeCase(.{
        .name = "fowler/basic/basic213",
        .pattern = "^([^!]+!)?([^!]+)$|^.+!([^!]+!)([^!]+)$",
        .input = .{ .haystack = "foo!bas", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 4 },
            .{ .start = 4, .end = 7 },
            null,
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic214" {
    try executeCase(.{
        .name = "fowler/basic/basic214",
        .pattern = "^(([^!]+!)?([^!]+)|.+!([^!]+!)([^!]+))$",
        .input = .{ .haystack = "bas", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            .{ .start = 0, .end = 3 },
            null,
            .{ .start = 0, .end = 3 },
            null,
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic215" {
    try executeCase(.{
        .name = "fowler/basic/basic215",
        .pattern = "^(([^!]+!)?([^!]+)|.+!([^!]+!)([^!]+))$",
        .input = .{ .haystack = "bar!bas", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 4 },
            .{ .start = 4, .end = 7 },
            null,
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic216" {
    try executeCase(.{
        .name = "fowler/basic/basic216",
        .pattern = "^(([^!]+!)?([^!]+)|.+!([^!]+!)([^!]+))$",
        .input = .{ .haystack = "foo!bar!bas", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 11 },
            .{ .start = 0, .end = 11 },
            null,
            null,
            .{ .start = 4, .end = 8 },
            .{ .start = 8, .end = 11 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic217" {
    try executeCase(.{
        .name = "fowler/basic/basic217",
        .pattern = "^(([^!]+!)?([^!]+)|.+!([^!]+!)([^!]+))$",
        .input = .{ .haystack = "foo!bas", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 4 },
            .{ .start = 4, .end = 7 },
            null,
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic218" {
    try executeCase(.{
        .name = "fowler/basic/basic218",
        .pattern = ".*(/XXX).*",
        .input = .{ .haystack = "/XXX", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 0, .end = 4 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic219" {
    try executeCase(.{
        .name = "fowler/basic/basic219",
        .pattern = ".*(\\\\XXX).*",
        .input = .{ .haystack = "\\XXX", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 0, .end = 4 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic220" {
    try executeCase(.{
        .name = "fowler/basic/basic220",
        .pattern = "\\\\XXX",
        .input = .{ .haystack = "\\XXX", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 4 }},
        .requires = caps.requires(.{ .input_anchored = true }),
    });
}

test "fowler/basic/basic221" {
    try executeCase(.{
        .name = "fowler/basic/basic221",
        .pattern = ".*(/000).*",
        .input = .{ .haystack = "/000", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 0, .end = 4 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic222" {
    try executeCase(.{
        .name = "fowler/basic/basic222",
        .pattern = ".*(\\\\000).*",
        .input = .{ .haystack = "\\000", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 0, .end = 4 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/basic/basic223" {
    try executeCase(.{
        .name = "fowler/basic/basic223",
        .pattern = "\\\\000",
        .input = .{ .haystack = "\\000", .anchored = true },
        .expected = &[_]?Match{.{ .start = 0, .end = 4 }},
        .requires = caps.requires(.{ .input_anchored = true }),
    });
}
