const harness = @import("../harness.zig");

pub const suite: harness.Suite = .{
    .name = "fowler/basic",
    .cases = &cases,
};

const cases = [_]harness.Case{
    .{
        .name = "basic3",
        .pattern = "abracadabra$",
        .haystack = "abracadabracadabra",
        .expected = .one(.{ 7, 18 }),
    },
    .{
        .name = "basic4",
        .pattern = "a...b",
        .haystack = "abababbb",
        .expected = .one(.{ 2, 7 }),
    },
    .{
        .name = "basic5",
        .pattern = "XXXXXX",
        .haystack = "..XXXXXX",
        .expected = .one(.{ 2, 8 }),
    },
    .{
        .name = "basic6",
        .pattern = "\\)",
        .haystack = "()",
        .expected = .one(.{ 1, 2 }),
    },
    .{
        .name = "basic7",
        .pattern = "a]",
        .haystack = "a]a",
        .anchored = true,
        .expected = .one(.{ 0, 2 }),
    },
    .{
        .name = "basic9",
        .pattern = "\\}",
        .haystack = "}",
        .anchored = true,
        .expected = .one(.{ 0, 1 }),
    },
    .{
        .name = "basic10",
        .pattern = "\\]",
        .haystack = "]",
        .anchored = true,
        .expected = .one(.{ 0, 1 }),
    },
    .{
        .name = "basic12",
        .pattern = "]",
        .haystack = "]",
        .anchored = true,
        .expected = .one(.{ 0, 1 }),
    },
    .{
        .name = "basic15",
        .pattern = "^a",
        .haystack = "ax",
        .anchored = true,
        .expected = .one(.{ 0, 1 }),
    },
    .{
        .name = "basic16",
        .pattern = "\\^a",
        .haystack = "a^a",
        .expected = .one(.{ 1, 3 }),
    },
    .{
        .name = "basic17",
        .pattern = "a\\^",
        .haystack = "a^",
        .anchored = true,
        .expected = .one(.{ 0, 2 }),
    },
    .{
        .name = "basic18",
        .pattern = "a$",
        .haystack = "aa",
        .expected = .one(.{ 1, 2 }),
    },
    .{
        .name = "basic19",
        .pattern = "a\\$",
        .haystack = "a$",
        .anchored = true,
        .expected = .one(.{ 0, 2 }),
    },
    .{
        .name = "basic20",
        .pattern = "^$",
        .haystack = "",
        .anchored = true,
        .expected = .one(.{ 0, 0 }),
    },
    .{
        .name = "basic21",
        .pattern = "$^",
        .haystack = "",
        .anchored = true,
        .expected = .one(.{ 0, 0 }),
    },
    .{
        .name = "basic22",
        .pattern = "a($)",
        .haystack = "aa",
        .expected = .capt(&.{ .{ 1, 2 }, .{ 2, 2 } }),
    },
    .{
        .name = "basic23",
        .pattern = "a*(^a)",
        .haystack = "aa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 } }),
    },
    .{
        .name = "basic24",
        .pattern = "(..)*(...)*",
        .haystack = "a",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 0 }, null, null }),
    },
    .{
        .name = "basic25",
        .pattern = "(..)*(...)*",
        .haystack = "abcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 2, 4 }, null }),
    },
    .{
        .name = "basic26",
        .pattern = "(ab|a)(bc|c)",
        .haystack = "abc",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 3 }, .{ 0, 2 }, .{ 2, 3 } }),
    },
    .{
        .name = "basic27",
        .pattern = "(ab)c|abc",
        .haystack = "abc",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 3 }, .{ 0, 2 } }),
    },
    .{
        .name = "basic28",
        .pattern = "a{0}b",
        .haystack = "ab",
        .expected = .one(.{ 1, 2 }),
    },
    .{
        .name = "basic29",
        .pattern = "(a*)(b?)(b+)b{3}",
        .haystack = "aaabbbbbbb",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 10 }, .{ 0, 3 }, .{ 3, 4 }, .{ 4, 7 } }),
    },
    .{
        .name = "basic30",
        .pattern = "(a*)(b{0,1})(b{1,})b{3}",
        .haystack = "aaabbbbbbb",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 10 }, .{ 0, 3 }, .{ 3, 4 }, .{ 4, 7 } }),
    },
    .{
        .name = "basic32",
        .pattern = "((a|a)|a)",
        .haystack = "a",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 }, .{ 0, 1 } }),
    },
    .{
        .name = "basic33",
        .pattern = "(a*)(a|aa)",
        .haystack = "aaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 0, 3 }, .{ 3, 4 } }),
    },
    .{
        .name = "basic34",
        .pattern = "a*(a.|aa)",
        .haystack = "aaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 2, 4 } }),
    },
    .{
        .name = "basic35",
        .pattern = "a(b)|c(d)|a(e)f",
        .haystack = "aef",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 3 }, null, null, .{ 1, 2 } }),
    },
    .{
        .name = "basic36",
        .pattern = "(a|b)?.*",
        .haystack = "b",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 } }),
    },
    .{
        .name = "basic37",
        .pattern = "(a|b)c|a(b|c)",
        .haystack = "ac",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 0, 1 }, null }),
    },
    .{
        .name = "basic38",
        .pattern = "(a|b)c|a(b|c)",
        .haystack = "ab",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, null, .{ 1, 2 } }),
    },
    .{
        .name = "basic39",
        .pattern = "(a|b)*c|(a|ab)*c",
        .haystack = "abc",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 3 }, .{ 1, 2 }, null }),
    },
    .{
        .name = "basic40",
        .pattern = "(a|b)*c|(a|ab)*c",
        .haystack = "xc",
        .expected = .capt(&.{ .{ 1, 2 }, null, null }),
    },
    .{
        .name = "basic41",
        .pattern = "(.a|.b).*|.*(.a|.b)",
        .haystack = "xa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 0, 2 }, null }),
    },
    .{
        .name = "basic42",
        .pattern = "a?(ab|ba)ab",
        .haystack = "abab",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 0, 2 } }),
    },
    .{
        .name = "basic43",
        .pattern = "a?(ac{0}b|ba)ab",
        .haystack = "abab",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 0, 2 } }),
    },
    .{
        .name = "basic44",
        .pattern = "ab|abab",
        .haystack = "abbabab",
        .anchored = true,
        .expected = .one(.{ 0, 2 }),
    },
    .{
        .name = "basic45",
        .pattern = "aba|bab|bba",
        .haystack = "baaabbbaba",
        .expected = .one(.{ 5, 8 }),
    },
    .{
        .name = "basic46",
        .pattern = "aba|bab",
        .haystack = "baaabbbaba",
        .expected = .one(.{ 6, 9 }),
    },
    .{
        .name = "basic47",
        .pattern = "(aa|aaa)*|(a|aaaaa)",
        .haystack = "aa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 0, 2 }, null }),
    },
    .{
        .name = "basic48",
        .pattern = "(a.|.a.)*|(a|.a...)",
        .haystack = "aa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 0, 2 }, null }),
    },
    .{
        .name = "basic49",
        .pattern = "ab|a",
        .haystack = "xabc",
        .expected = .one(.{ 1, 3 }),
    },
    .{
        .name = "basic50",
        .pattern = "ab|a",
        .haystack = "xxabc",
        .expected = .one(.{ 2, 4 }),
    },
    .{
        .name = "basic51",
        .pattern = "(Ab|cD)*",
        .haystack = "aBcD",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 2, 4 } }),
        .options = .{ .syntax = .{
            .case_insensitive = true,
        } },
    },
    .{
        .name = "basic52",
        .pattern = "[^-]",
        .haystack = "--a",
        .expected = .one(.{ 2, 3 }),
    },
    .{
        .name = "basic53",
        .pattern = "[a-]*",
        .haystack = "--a",
        .anchored = true,
        .expected = .one(.{ 0, 3 }),
    },
    .{
        .name = "basic54",
        .pattern = "[a-m-]*",
        .haystack = "--amoma--",
        .anchored = true,
        .expected = .one(.{ 0, 4 }),
    },
    .{
        .name = "basic55",
        .pattern = ":::1:::0:|:::1:1:0:",
        .haystack = ":::0:::1:::1:::0:",
        .expected = .one(.{ 8, 17 }),
    },
    .{
        .name = "basic56",
        .pattern = ":::1:::0:|:::1:1:1:",
        .haystack = ":::0:::1:::1:::0:",
        .expected = .one(.{ 8, 17 }),
    },
    .{
        .name = "basic57",
        .pattern = "[[:upper:]]",
        .haystack = "A",
        .anchored = true,
        .expected = .one(.{ 0, 1 }),
    },
    .{
        .name = "basic58",
        .pattern = "[[:lower:]]+",
        .haystack = "`az{",
        .expected = .one(.{ 1, 3 }),
    },
    .{
        .name = "basic59",
        .pattern = "[[:upper:]]+",
        .haystack = "@AZ[",
        .expected = .one(.{ 1, 3 }),
    },
    .{
        .name = "basic65",
        .pattern = "\\n",
        .haystack = "\n",
        .anchored = true,
        .expected = .one(.{ 0, 1 }),
    },
    .{
        .name = "basic66",
        .pattern = "\\n",
        .haystack = "\n",
        .anchored = true,
        .expected = .one(.{ 0, 1 }),
    },
    .{
        .name = "basic67",
        .pattern = "[^a]",
        .haystack = "\n",
        .anchored = true,
        .expected = .one(.{ 0, 1 }),
    },
    .{
        .name = "basic68",
        .pattern = "\\na",
        .haystack = "\na",
        .anchored = true,
        .expected = .one(.{ 0, 2 }),
    },
    .{
        .name = "basic69",
        .pattern = "(a)(b)(c)",
        .haystack = "abc",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 3 }, .{ 0, 1 }, .{ 1, 2 }, .{ 2, 3 } }),
    },
    .{
        .name = "basic70",
        .pattern = "xxx",
        .haystack = "xxx",
        .anchored = true,
        .expected = .one(.{ 0, 3 }),
    },
    .{
        .name = "basic72",
        .pattern = "(?:^|[ (,;])(?:(?:(?:[Ff]eb[^ ]* *|0*2/|\\* */?)0*[6-7]))(?:[^0-9]|$)",
        .haystack = "feb 6,",
        .anchored = true,
        .expected = .one(.{ 0, 6 }),
    },
    .{
        .name = "basic74",
        .pattern = "(?:^|[ (,;])(?:(?:(?:[Ff]eb[^ ]* *|0*2/|\\* */?)0*[6-7]))(?:[^0-9]|$)",
        .haystack = "2/7",
        .anchored = true,
        .expected = .one(.{ 0, 3 }),
    },
    .{
        .name = "basic76",
        .pattern = "(?:^|[ (,;])(?:(?:(?:[Ff]eb[^ ]* *|0*2/|\\* */?)0*[6-7]))(?:[^0-9]|$)",
        .haystack = "feb 1,Feb 6",
        .expected = .one(.{ 5, 11 }),
    },
    .{
        .name = "basic78",
        .pattern = "(((?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:x))))))))))))))))))))))))))))))",
        .haystack = "x",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 }, .{ 0, 1 } }),
    },
    .{
        .name = "basic80",
        .pattern = "(((?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:x))))))))))))))))))))))))))))))*",
        .haystack = "xx",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 1, 2 }, .{ 1, 2 } }),
    },
    .{
        .name = "basic81",
        .pattern = "a?(ab|ba)*",
        .haystack = "ababababababababababababababababababababababababababababababababababababababababa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 81 }, .{ 79, 81 } }),
    },
    .{
        .name = "basic82",
        .pattern = "abaa|abbaa|abbbaa|abbbbaa",
        .haystack = "ababbabbbabbbabbbbabbbbaa",
        .expected = .one(.{ 18, 25 }),
    },
    .{
        .name = "basic83",
        .pattern = "abaa|abbaa|abbbaa|abbbbaa",
        .haystack = "ababbabbbabbbabbbbabaa",
        .expected = .one(.{ 18, 22 }),
    },
    .{
        .name = "basic84",
        .pattern = "aaac|aabc|abac|abbc|baac|babc|bbac|bbbc",
        .haystack = "baaabbbabac",
        .expected = .one(.{ 7, 11 }),
    },
    .{
        .name = "basic86",
        .pattern = ".*",
        .haystack = "\x01\x7f",
        .anchored = true,
        .expected = .one(.{ 0, 2 }),
    },
    .{
        .name = "basic87",
        .pattern = "aaaa|bbbb|cccc|ddddd|eeeeee|fffffff|gggg|hhhh|iiiii|jjjjj|kkkkk|llll",
        .haystack = "XaaaXbbbXcccXdddXeeeXfffXgggXhhhXiiiXjjjXkkkXlllXcbaXaaaa",
        .expected = .one(.{ 53, 57 }),
    },
    .{
        .name = "basic89",
        .pattern = "a*a*a*a*a*b",
        .haystack = "aaaaaaaaab",
        .anchored = true,
        .expected = .one(.{ 0, 10 }),
    },
    .{
        .name = "basic90",
        .pattern = "^",
        .haystack = "",
        .anchored = true,
        .expected = .one(.{ 0, 0 }),
    },
    .{
        .name = "basic91",
        .pattern = "$",
        .haystack = "",
        .anchored = true,
        .expected = .one(.{ 0, 0 }),
    },
    .{
        .name = "basic92",
        .pattern = "^$",
        .haystack = "",
        .anchored = true,
        .expected = .one(.{ 0, 0 }),
    },
    .{
        .name = "basic93",
        .pattern = "^a$",
        .haystack = "a",
        .anchored = true,
        .expected = .one(.{ 0, 1 }),
    },
    .{
        .name = "basic94",
        .pattern = "abc",
        .haystack = "abc",
        .anchored = true,
        .expected = .one(.{ 0, 3 }),
    },
    .{
        .name = "basic95",
        .pattern = "abc",
        .haystack = "xabcy",
        .expected = .one(.{ 1, 4 }),
    },
    .{
        .name = "basic96",
        .pattern = "abc",
        .haystack = "ababc",
        .expected = .one(.{ 2, 5 }),
    },
    .{
        .name = "basic97",
        .pattern = "ab*c",
        .haystack = "abc",
        .anchored = true,
        .expected = .one(.{ 0, 3 }),
    },
    .{
        .name = "basic98",
        .pattern = "ab*bc",
        .haystack = "abc",
        .anchored = true,
        .expected = .one(.{ 0, 3 }),
    },
    .{
        .name = "basic99",
        .pattern = "ab*bc",
        .haystack = "abbc",
        .anchored = true,
        .expected = .one(.{ 0, 4 }),
    },
    .{
        .name = "basic100",
        .pattern = "ab*bc",
        .haystack = "abbbbc",
        .anchored = true,
        .expected = .one(.{ 0, 6 }),
    },
    .{
        .name = "basic101",
        .pattern = "ab+bc",
        .haystack = "abbc",
        .anchored = true,
        .expected = .one(.{ 0, 4 }),
    },
    .{
        .name = "basic102",
        .pattern = "ab+bc",
        .haystack = "abbbbc",
        .anchored = true,
        .expected = .one(.{ 0, 6 }),
    },
    .{
        .name = "basic103",
        .pattern = "ab?bc",
        .haystack = "abbc",
        .anchored = true,
        .expected = .one(.{ 0, 4 }),
    },
    .{
        .name = "basic104",
        .pattern = "ab?bc",
        .haystack = "abc",
        .anchored = true,
        .expected = .one(.{ 0, 3 }),
    },
    .{
        .name = "basic105",
        .pattern = "ab?c",
        .haystack = "abc",
        .anchored = true,
        .expected = .one(.{ 0, 3 }),
    },
    .{
        .name = "basic106",
        .pattern = "^abc$",
        .haystack = "abc",
        .anchored = true,
        .expected = .one(.{ 0, 3 }),
    },
    .{
        .name = "basic107",
        .pattern = "^abc",
        .haystack = "abcc",
        .anchored = true,
        .expected = .one(.{ 0, 3 }),
    },
    .{
        .name = "basic108",
        .pattern = "abc$",
        .haystack = "aabc",
        .expected = .one(.{ 1, 4 }),
    },
    .{
        .name = "basic109",
        .pattern = "^",
        .haystack = "abc",
        .anchored = true,
        .expected = .one(.{ 0, 0 }),
    },
    .{
        .name = "basic110",
        .pattern = "$",
        .haystack = "abc",
        .expected = .one(.{ 3, 3 }),
    },
    .{
        .name = "basic111",
        .pattern = "a.c",
        .haystack = "abc",
        .anchored = true,
        .expected = .one(.{ 0, 3 }),
    },
    .{
        .name = "basic112",
        .pattern = "a.c",
        .haystack = "axc",
        .anchored = true,
        .expected = .one(.{ 0, 3 }),
    },
    .{
        .name = "basic113",
        .pattern = "a.*c",
        .haystack = "axyzc",
        .anchored = true,
        .expected = .one(.{ 0, 5 }),
    },
    .{
        .name = "basic114",
        .pattern = "a[bc]d",
        .haystack = "abd",
        .anchored = true,
        .expected = .one(.{ 0, 3 }),
    },
    .{
        .name = "basic115",
        .pattern = "a[b-d]e",
        .haystack = "ace",
        .anchored = true,
        .expected = .one(.{ 0, 3 }),
    },
    .{
        .name = "basic116",
        .pattern = "a[b-d]",
        .haystack = "aac",
        .expected = .one(.{ 1, 3 }),
    },
    .{
        .name = "basic117",
        .pattern = "a[-b]",
        .haystack = "a-",
        .anchored = true,
        .expected = .one(.{ 0, 2 }),
    },
    .{
        .name = "basic118",
        .pattern = "a[b-]",
        .haystack = "a-",
        .anchored = true,
        .expected = .one(.{ 0, 2 }),
    },
    .{
        .name = "basic119",
        .pattern = "a]",
        .haystack = "a]",
        .anchored = true,
        .expected = .one(.{ 0, 2 }),
    },
    .{
        .name = "basic120",
        .pattern = "a[]]b",
        .haystack = "a]b",
        .anchored = true,
        .expected = .one(.{ 0, 3 }),
    },
    .{
        .name = "basic121",
        .pattern = "a[^bc]d",
        .haystack = "aed",
        .anchored = true,
        .expected = .one(.{ 0, 3 }),
    },
    .{
        .name = "basic122",
        .pattern = "a[^-b]c",
        .haystack = "adc",
        .anchored = true,
        .expected = .one(.{ 0, 3 }),
    },
    .{
        .name = "basic123",
        .pattern = "a[^]b]c",
        .haystack = "adc",
        .anchored = true,
        .expected = .one(.{ 0, 3 }),
    },
    .{
        .name = "basic124",
        .pattern = "ab|cd",
        .haystack = "abc",
        .anchored = true,
        .expected = .one(.{ 0, 2 }),
    },
    .{
        .name = "basic125",
        .pattern = "ab|cd",
        .haystack = "abcd",
        .anchored = true,
        .expected = .one(.{ 0, 2 }),
    },
    .{
        .name = "basic126",
        .pattern = "a\\(b",
        .haystack = "a(b",
        .anchored = true,
        .expected = .one(.{ 0, 3 }),
    },
    .{
        .name = "basic127",
        .pattern = "a\\(*b",
        .haystack = "ab",
        .anchored = true,
        .expected = .one(.{ 0, 2 }),
    },
    .{
        .name = "basic128",
        .pattern = "a\\(*b",
        .haystack = "a((b",
        .anchored = true,
        .expected = .one(.{ 0, 4 }),
    },
    .{
        .name = "basic129",
        .pattern = "((a))",
        .haystack = "abc",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 }, .{ 0, 1 } }),
    },
    .{
        .name = "basic130",
        .pattern = "(a)b(c)",
        .haystack = "abc",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 3 }, .{ 0, 1 }, .{ 2, 3 } }),
    },
    .{
        .name = "basic131",
        .pattern = "a+b+c",
        .haystack = "aabbabc",
        .expected = .one(.{ 4, 7 }),
    },
    .{
        .name = "basic132",
        .pattern = "a*",
        .haystack = "aaa",
        .anchored = true,
        .expected = .one(.{ 0, 3 }),
    },
    .{
        .name = "basic133",
        .pattern = "(a*)*",
        .haystack = "-",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 0 }, .{ 0, 0 } }),
    },
    .{
        .name = "basic134",
        .pattern = "(a*)+",
        .haystack = "-",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 0 }, .{ 0, 0 } }),
    },
    .{
        .name = "basic135",
        .pattern = "(a*|b)*",
        .haystack = "-",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 0 }, .{ 0, 0 } }),
    },
    .{
        .name = "basic136",
        .pattern = "(a+|b)*",
        .haystack = "ab",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 1, 2 } }),
    },
    .{
        .name = "basic137",
        .pattern = "(a+|b)+",
        .haystack = "ab",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 1, 2 } }),
    },
    .{
        .name = "basic138",
        .pattern = "(a+|b)?",
        .haystack = "ab",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 } }),
    },
    .{
        .name = "basic139",
        .pattern = "[^ab]*",
        .haystack = "cde",
        .anchored = true,
        .expected = .one(.{ 0, 3 }),
    },
    .{
        .name = "basic140",
        .pattern = "(^)*",
        .haystack = "-",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 0 }, .{ 0, 0 } }),
    },
    .{
        .name = "basic141",
        .pattern = "a*",
        .haystack = "",
        .anchored = true,
        .expected = .one(.{ 0, 0 }),
    },
    .{
        .name = "basic142",
        .pattern = "([abc])*d",
        .haystack = "abbbcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 4, 5 } }),
    },
    .{
        .name = "basic143",
        .pattern = "([abc])*bcd",
        .haystack = "abcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 0, 1 } }),
    },
    .{
        .name = "basic144",
        .pattern = "a|b|c|d|e",
        .haystack = "e",
        .anchored = true,
        .expected = .one(.{ 0, 1 }),
    },
    .{
        .name = "basic145",
        .pattern = "(a|b|c|d|e)f",
        .haystack = "ef",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 0, 1 } }),
    },
    .{
        .name = "basic146",
        .pattern = "((a*|b))*",
        .haystack = "-",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 0 }, .{ 0, 0 }, .{ 0, 0 } }),
    },
    .{
        .name = "basic147",
        .pattern = "abcd*efg",
        .haystack = "abcdefg",
        .anchored = true,
        .expected = .one(.{ 0, 7 }),
    },
    .{
        .name = "basic148",
        .pattern = "ab*",
        .haystack = "xabyabbbz",
        .expected = .one(.{ 1, 3 }),
    },
    .{
        .name = "basic149",
        .pattern = "ab*",
        .haystack = "xayabbbz",
        .expected = .one(.{ 1, 2 }),
    },
    .{
        .name = "basic150",
        .pattern = "(ab|cd)e",
        .haystack = "abcde",
        .expected = .capt(&.{ .{ 2, 5 }, .{ 2, 4 } }),
    },
    .{
        .name = "basic151",
        .pattern = "[abhgefdc]ij",
        .haystack = "hij",
        .anchored = true,
        .expected = .one(.{ 0, 3 }),
    },
    .{
        .name = "basic152",
        .pattern = "(a|b)c*d",
        .haystack = "abcd",
        .expected = .capt(&.{ .{ 1, 4 }, .{ 1, 2 } }),
    },
    .{
        .name = "basic153",
        .pattern = "(ab|ab*)bc",
        .haystack = "abc",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 3 }, .{ 0, 1 } }),
    },
    .{
        .name = "basic154",
        .pattern = "a([bc]*)c*",
        .haystack = "abc",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 3 }, .{ 1, 3 } }),
    },
    .{
        .name = "basic155",
        .pattern = "a([bc]*)(c*d)",
        .haystack = "abcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 1, 3 }, .{ 3, 4 } }),
    },
    .{
        .name = "basic156",
        .pattern = "a([bc]+)(c*d)",
        .haystack = "abcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 1, 3 }, .{ 3, 4 } }),
    },
    .{
        .name = "basic157",
        .pattern = "a([bc]*)(c+d)",
        .haystack = "abcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 1, 2 }, .{ 2, 4 } }),
    },
    .{
        .name = "basic158",
        .pattern = "a[bcd]*dcdcde",
        .haystack = "adcdcde",
        .anchored = true,
        .expected = .one(.{ 0, 7 }),
    },
    .{
        .name = "basic159",
        .pattern = "(ab|a)b*c",
        .haystack = "abc",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 3 }, .{ 0, 2 } }),
    },
    .{
        .name = "basic160",
        .pattern = "((a)(b)c)(d)",
        .haystack = "abcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 0, 3 }, .{ 0, 1 }, .{ 1, 2 }, .{ 3, 4 } }),
    },
    .{
        .name = "basic161",
        .pattern = "[A-Za-z_][A-Za-z0-9_]*",
        .haystack = "alpha",
        .anchored = true,
        .expected = .one(.{ 0, 5 }),
    },
    .{
        .name = "basic162",
        .pattern = "^a(bc+|b[eh])g|.h$",
        .haystack = "abh",
        .expected = .capt(&.{ .{ 1, 3 }, null }),
    },
    .{
        .name = "basic163",
        .pattern = "(bc+d$|ef*g.|h?i(j|k))",
        .haystack = "effgz",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 5 }, .{ 0, 5 }, null }),
    },
    .{
        .name = "basic164",
        .pattern = "(bc+d$|ef*g.|h?i(j|k))",
        .haystack = "ij",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 0, 2 }, .{ 1, 2 } }),
    },
    .{
        .name = "basic165",
        .pattern = "(bc+d$|ef*g.|h?i(j|k))",
        .haystack = "reffgz",
        .expected = .capt(&.{ .{ 1, 6 }, .{ 1, 6 }, null }),
    },
    .{
        .name = "basic166",
        .pattern = "(((((((((a)))))))))",
        .haystack = "a",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 }, .{ 0, 1 }, .{ 0, 1 }, .{ 0, 1 }, .{ 0, 1 }, .{ 0, 1 }, .{ 0, 1 }, .{ 0, 1 }, .{ 0, 1 } }),
    },
    .{
        .name = "basic167",
        .pattern = "multiple words",
        .haystack = "multiple words yeah",
        .anchored = true,
        .expected = .one(.{ 0, 14 }),
    },
    .{
        .name = "basic168",
        .pattern = "(.*)c(.*)",
        .haystack = "abcde",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 5 }, .{ 0, 2 }, .{ 3, 5 } }),
    },
    .{
        .name = "basic169",
        .pattern = "abcd",
        .haystack = "abcd",
        .anchored = true,
        .expected = .one(.{ 0, 4 }),
    },
    .{
        .name = "basic170",
        .pattern = "a(bc)d",
        .haystack = "abcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 1, 3 } }),
    },
    .{
        .name = "basic171",
        .pattern = "a[\\x01-\\x03]?c",
        .haystack = "a\x02c",
        .anchored = true,
        .expected = .one(.{ 0, 3 }),
    },
    .{
        .name = "basic172",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Muammar Qaddafi",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 15 }, null, .{ 10, 12 } }),
    },
    .{
        .name = "basic173",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Mo'ammar Gadhafi",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 16 }, null, .{ 11, 13 } }),
    },
    .{
        .name = "basic174",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Muammar Kaddafi",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 15 }, null, .{ 10, 12 } }),
    },
    .{
        .name = "basic175",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Muammar Qadhafi",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 15 }, null, .{ 10, 12 } }),
    },
    .{
        .name = "basic176",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Muammar Gadafi",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 14 }, null, .{ 10, 11 } }),
    },
    .{
        .name = "basic177",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Mu'ammar Qadafi",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 15 }, null, .{ 11, 12 } }),
    },
    .{
        .name = "basic178",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Moamar Gaddafi",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 14 }, null, .{ 9, 11 } }),
    },
    .{
        .name = "basic179",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Mu'ammar Qadhdhafi",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 18 }, null, .{ 13, 15 } }),
    },
    .{
        .name = "basic180",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Muammar Khaddafi",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 16 }, null, .{ 11, 13 } }),
    },
    .{
        .name = "basic181",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Muammar Ghaddafy",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 16 }, null, .{ 11, 13 } }),
    },
    .{
        .name = "basic182",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Muammar Ghadafi",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 15 }, null, .{ 11, 12 } }),
    },
    .{
        .name = "basic183",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Muammar Ghaddafi",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 16 }, null, .{ 11, 13 } }),
    },
    .{
        .name = "basic184",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Muamar Kaddafi",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 14 }, null, .{ 9, 11 } }),
    },
    .{
        .name = "basic185",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Muammar Quathafi",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 16 }, null, .{ 11, 13 } }),
    },
    .{
        .name = "basic186",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Muammar Gheddafi",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 16 }, null, .{ 11, 13 } }),
    },
    .{
        .name = "basic187",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Moammar Khadafy",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 15 }, null, .{ 11, 12 } }),
    },
    .{
        .name = "basic188",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Moammar Qudhafi",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 15 }, null, .{ 10, 12 } }),
    },
    .{
        .name = "basic189",
        .pattern = "a+(b|c)*d+",
        .haystack = "aabcdd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 3, 4 } }),
    },
    .{
        .name = "basic190",
        .pattern = "^.+$",
        .haystack = "vivi",
        .anchored = true,
        .expected = .one(.{ 0, 4 }),
    },
    .{
        .name = "basic191",
        .pattern = "^(.+)$",
        .haystack = "vivi",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 0, 4 } }),
    },
    .{
        .name = "basic192",
        .pattern = "^([^!.]+).att.com!(.+)$",
        .haystack = "gryphon.att.com!eby",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 19 }, .{ 0, 7 }, .{ 16, 19 } }),
    },
    .{
        .name = "basic193",
        .pattern = "^([^!]+!)?([^!]+)$",
        .haystack = "bas",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 3 }, null, .{ 0, 3 } }),
    },
    .{
        .name = "basic194",
        .pattern = "^([^!]+!)?([^!]+)$",
        .haystack = "bar!bas",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 7 }, .{ 0, 4 }, .{ 4, 7 } }),
    },
    .{
        .name = "basic195",
        .pattern = "^([^!]+!)?([^!]+)$",
        .haystack = "foo!bas",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 7 }, .{ 0, 4 }, .{ 4, 7 } }),
    },
    .{
        .name = "basic196",
        .pattern = "^.+!([^!]+!)([^!]+)$",
        .haystack = "foo!bar!bas",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 11 }, .{ 4, 8 }, .{ 8, 11 } }),
    },
    .{
        .name = "basic197",
        .pattern = "((foo)|(bar))!bas",
        .haystack = "bar!bas",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 7 }, .{ 0, 3 }, null, .{ 0, 3 } }),
    },
    .{
        .name = "basic198",
        .pattern = "((foo)|(bar))!bas",
        .haystack = "foo!bar!bas",
        .expected = .capt(&.{ .{ 4, 11 }, .{ 4, 7 }, null, .{ 4, 7 } }),
    },
    .{
        .name = "basic199",
        .pattern = "((foo)|(bar))!bas",
        .haystack = "foo!bas",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 7 }, .{ 0, 3 }, .{ 0, 3 }, null }),
    },
    .{
        .name = "basic200",
        .pattern = "((foo)|bar)!bas",
        .haystack = "bar!bas",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 7 }, .{ 0, 3 }, null }),
    },
    .{
        .name = "basic201",
        .pattern = "((foo)|bar)!bas",
        .haystack = "foo!bar!bas",
        .expected = .capt(&.{ .{ 4, 11 }, .{ 4, 7 }, null }),
    },
    .{
        .name = "basic202",
        .pattern = "((foo)|bar)!bas",
        .haystack = "foo!bas",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 7 }, .{ 0, 3 }, .{ 0, 3 } }),
    },
    .{
        .name = "basic203",
        .pattern = "(foo|(bar))!bas",
        .haystack = "bar!bas",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 7 }, .{ 0, 3 }, .{ 0, 3 } }),
    },
    .{
        .name = "basic204",
        .pattern = "(foo|(bar))!bas",
        .haystack = "foo!bar!bas",
        .expected = .capt(&.{ .{ 4, 11 }, .{ 4, 7 }, .{ 4, 7 } }),
    },
    .{
        .name = "basic205",
        .pattern = "(foo|(bar))!bas",
        .haystack = "foo!bas",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 7 }, .{ 0, 3 }, null }),
    },
    .{
        .name = "basic206",
        .pattern = "(foo|bar)!bas",
        .haystack = "bar!bas",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 7 }, .{ 0, 3 } }),
    },
    .{
        .name = "basic207",
        .pattern = "(foo|bar)!bas",
        .haystack = "foo!bar!bas",
        .expected = .capt(&.{ .{ 4, 11 }, .{ 4, 7 } }),
    },
    .{
        .name = "basic208",
        .pattern = "(foo|bar)!bas",
        .haystack = "foo!bas",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 7 }, .{ 0, 3 } }),
    },
    .{
        .name = "basic209",
        .pattern = "^(([^!]+!)?([^!]+)|.+!([^!]+!)([^!]+))$",
        .haystack = "foo!bar!bas",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 11 }, .{ 0, 11 }, null, null, .{ 4, 8 }, .{ 8, 11 } }),
    },
    .{
        .name = "basic210",
        .pattern = "^([^!]+!)?([^!]+)$|^.+!([^!]+!)([^!]+)$",
        .haystack = "bas",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 3 }, null, .{ 0, 3 }, null, null }),
    },
    .{
        .name = "basic211",
        .pattern = "^([^!]+!)?([^!]+)$|^.+!([^!]+!)([^!]+)$",
        .haystack = "bar!bas",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 7 }, .{ 0, 4 }, .{ 4, 7 }, null, null }),
    },
    .{
        .name = "basic212",
        .pattern = "^([^!]+!)?([^!]+)$|^.+!([^!]+!)([^!]+)$",
        .haystack = "foo!bar!bas",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 11 }, null, null, .{ 4, 8 }, .{ 8, 11 } }),
    },
    .{
        .name = "basic213",
        .pattern = "^([^!]+!)?([^!]+)$|^.+!([^!]+!)([^!]+)$",
        .haystack = "foo!bas",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 7 }, .{ 0, 4 }, .{ 4, 7 }, null, null }),
    },
    .{
        .name = "basic214",
        .pattern = "^(([^!]+!)?([^!]+)|.+!([^!]+!)([^!]+))$",
        .haystack = "bas",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 3 }, .{ 0, 3 }, null, .{ 0, 3 }, null, null }),
    },
    .{
        .name = "basic215",
        .pattern = "^(([^!]+!)?([^!]+)|.+!([^!]+!)([^!]+))$",
        .haystack = "bar!bas",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 7 }, .{ 0, 7 }, .{ 0, 4 }, .{ 4, 7 }, null, null }),
    },
    .{
        .name = "basic216",
        .pattern = "^(([^!]+!)?([^!]+)|.+!([^!]+!)([^!]+))$",
        .haystack = "foo!bar!bas",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 11 }, .{ 0, 11 }, null, null, .{ 4, 8 }, .{ 8, 11 } }),
    },
    .{
        .name = "basic217",
        .pattern = "^(([^!]+!)?([^!]+)|.+!([^!]+!)([^!]+))$",
        .haystack = "foo!bas",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 7 }, .{ 0, 7 }, .{ 0, 4 }, .{ 4, 7 }, null, null }),
    },
    .{
        .name = "basic218",
        .pattern = ".*(/XXX).*",
        .haystack = "/XXX",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 0, 4 } }),
    },
    .{
        .name = "basic219",
        .pattern = ".*(\\\\XXX).*",
        .haystack = "\\XXX",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 0, 4 } }),
    },
    .{
        .name = "basic220",
        .pattern = "\\\\XXX",
        .haystack = "\\XXX",
        .anchored = true,
        .expected = .one(.{ 0, 4 }),
    },
    .{
        .name = "basic221",
        .pattern = ".*(/000).*",
        .haystack = "/000",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 0, 4 } }),
    },
    .{
        .name = "basic222",
        .pattern = ".*(\\\\000).*",
        .haystack = "\\000",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 0, 4 } }),
    },
    .{
        .name = "basic223",
        .pattern = "\\\\000",
        .haystack = "\\000",
        .anchored = true,
        .expected = .one(.{ 0, 4 }),
    },
};
