//! GENERATED by `zig build gen-tests -- fowler`.
//! Source: tests/fowler/data/basic.toml
//! DO NOT EDIT.

const harness = @import("../harness.zig");
const runner = harness.runner;
const caps = harness.capabilities;
const Match = @import("export_test").Regex.Match;

pub const cases = [_]runner.Case{
    .{
        .name = "basic3",
        .pattern = "abracadabra$",
        .haystack = "abracadabracadabra",
        .expected = &[_]?Match{
            .{ .start = 7, .end = 18 },
        },
        .requires = caps.requires(.{ .anchor_line_end = true }),
    },
    .{
        .name = "basic4",
        .pattern = "a...b",
        .haystack = "abababbb",
        .expected = &[_]?Match{
            .{ .start = 2, .end = 7 },
        },
        .requires = caps.requires(.{ .dot = true }),
    },
    .{
        .name = "basic5",
        .pattern = "XXXXXX",
        .haystack = "..XXXXXX",
        .expected = &[_]?Match{
            .{ .start = 2, .end = 8 },
        },
    },
    .{
        .name = "basic6",
        .pattern = "\\)",
        .haystack = "()",
        .expected = &[_]?Match{
            .{ .start = 1, .end = 2 },
        },
    },
    .{
        .name = "basic7",
        .pattern = "a]",
        .haystack = "a]a",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    },
    .{
        .name = "basic9",
        .pattern = "\\}",
        .haystack = "}",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    },
    .{
        .name = "basic10",
        .pattern = "\\]",
        .haystack = "]",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    },
    .{
        .name = "basic12",
        .pattern = "]",
        .haystack = "]",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    },
    .{
        .name = "basic15",
        .pattern = "^a",
        .haystack = "ax",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .anchor_line_start = true, .input_anchored = true }),
    },
    .{
        .name = "basic16",
        .pattern = "\\^a",
        .haystack = "a^a",
        .expected = &[_]?Match{
            .{ .start = 1, .end = 3 },
        },
    },
    .{
        .name = "basic17",
        .pattern = "a\\^",
        .haystack = "a^",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    },
    .{
        .name = "basic18",
        .pattern = "a$",
        .haystack = "aa",
        .expected = &[_]?Match{
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .anchor_line_end = true }),
    },
    .{
        .name = "basic19",
        .pattern = "a\\$",
        .haystack = "a$",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    },
    .{
        .name = "basic20",
        .pattern = "^$",
        .haystack = "",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic21",
        .pattern = "$^",
        .haystack = "",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic22",
        .pattern = "a($)",
        .haystack = "aa",
        .expected = &[_]?Match{
            .{ .start = 1, .end = 2 },
            .{ .start = 2, .end = 2 },
        },
        .requires = caps.requires(.{ .anchor_line_end = true }),
    },
    .{
        .name = "basic23",
        .pattern = "a*(^a)",
        .haystack = "aa",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .anchor_line_start = true, .input_anchored = true }),
    },
    .{
        .name = "basic24",
        .pattern = "(..)*(...)*",
        .haystack = "a",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            null,
            null,
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic25",
        .pattern = "(..)*(...)*",
        .haystack = "abcd",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 2, .end = 4 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic26",
        .pattern = "(ab|a)(bc|c)",
        .haystack = "abc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            .{ .start = 0, .end = 2 },
            .{ .start = 2, .end = 3 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    },
    .{
        .name = "basic27",
        .pattern = "(ab)c|abc",
        .haystack = "abc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            .{ .start = 0, .end = 2 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    },
    .{
        .name = "basic28",
        .pattern = "a{0}b",
        .haystack = "ab",
        .expected = &[_]?Match{
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .rep_exact = true }),
    },
    .{
        .name = "basic29",
        .pattern = "(a*)(b?)(b+)b{3}",
        .haystack = "aaabbbbbbb",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 10 },
            .{ .start = 0, .end = 3 },
            .{ .start = 3, .end = 4 },
            .{ .start = 4, .end = 7 },
        },
        .requires = caps.requires(.{ .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .rep_exact = true, .input_anchored = true }),
    },
    .{
        .name = "basic30",
        .pattern = "(a*)(b{0,1})(b{1,})b{3}",
        .haystack = "aaabbbbbbb",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 10 },
            .{ .start = 0, .end = 3 },
            .{ .start = 3, .end = 4 },
            .{ .start = 4, .end = 7 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_exact = true, .rep_min = true, .rep_range = true, .input_anchored = true }),
    },
    .{
        .name = "basic32",
        .pattern = "((a|a)|a)",
        .haystack = "a",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    },
    .{
        .name = "basic33",
        .pattern = "(a*)(a|aa)",
        .haystack = "aaaa",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 0, .end = 3 },
            .{ .start = 3, .end = 4 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic34",
        .pattern = "a*(a.|aa)",
        .haystack = "aaaa",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 2, .end = 4 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic35",
        .pattern = "a(b)|c(d)|a(e)f",
        .haystack = "aef",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            null,
            null,
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    },
    .{
        .name = "basic36",
        .pattern = "(a|b)?.*",
        .haystack = "b",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic37",
        .pattern = "(a|b)c|a(b|c)",
        .haystack = "ac",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 1 },
            null,
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    },
    .{
        .name = "basic38",
        .pattern = "(a|b)c|a(b|c)",
        .haystack = "ab",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            null,
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    },
    .{
        .name = "basic39",
        .pattern = "(a|b)*c|(a|ab)*c",
        .haystack = "abc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            .{ .start = 1, .end = 2 },
            null,
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic40",
        .pattern = "(a|b)*c|(a|ab)*c",
        .haystack = "xc",
        .expected = &[_]?Match{
            .{ .start = 1, .end = 2 },
            null,
            null,
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true }),
    },
    .{
        .name = "basic41",
        .pattern = "(.a|.b).*|.*(.a|.b)",
        .haystack = "xa",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic42",
        .pattern = "a?(ab|ba)ab",
        .haystack = "abab",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 0, .end = 2 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_one = true, .input_anchored = true }),
    },
    .{
        .name = "basic43",
        .pattern = "a?(ac{0}b|ba)ab",
        .haystack = "abab",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 0, .end = 2 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_one = true, .rep_exact = true, .input_anchored = true }),
    },
    .{
        .name = "basic44",
        .pattern = "ab|abab",
        .haystack = "abbabab",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    },
    .{
        .name = "basic45",
        .pattern = "aba|bab|bba",
        .haystack = "baaabbbaba",
        .expected = &[_]?Match{
            .{ .start = 5, .end = 8 },
        },
        .requires = caps.requires(.{ .alternation = true }),
    },
    .{
        .name = "basic46",
        .pattern = "aba|bab",
        .haystack = "baaabbbaba",
        .expected = &[_]?Match{
            .{ .start = 6, .end = 9 },
        },
        .requires = caps.requires(.{ .alternation = true }),
    },
    .{
        .name = "basic47",
        .pattern = "(aa|aaa)*|(a|aaaaa)",
        .haystack = "aa",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            null,
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic48",
        .pattern = "(a.|.a.)*|(a|.a...)",
        .haystack = "aa",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic49",
        .pattern = "ab|a",
        .haystack = "xabc",
        .expected = &[_]?Match{
            .{ .start = 1, .end = 3 },
        },
        .requires = caps.requires(.{ .alternation = true }),
    },
    .{
        .name = "basic50",
        .pattern = "ab|a",
        .haystack = "xxabc",
        .expected = &[_]?Match{
            .{ .start = 2, .end = 4 },
        },
        .requires = caps.requires(.{ .alternation = true }),
    },
    .{
        .name = "basic51",
        .pattern = "(Ab|cD)*",
        .haystack = "aBcD",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 2, .end = 4 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .ignore_case = true, .input_anchored = true }),
    },
    .{
        .name = "basic52",
        .pattern = "[^-]",
        .haystack = "--a",
        .expected = &[_]?Match{
            .{ .start = 2, .end = 3 },
        },
        .requires = caps.requires(.{ .class_simple = true, .class_negated = true }),
    },
    .{
        .name = "basic53",
        .pattern = "[a-]*",
        .haystack = "--a",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic54",
        .pattern = "[a-m-]*",
        .haystack = "--amoma--",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .class_range = true, .input_anchored = true }),
    },
    .{
        .name = "basic55",
        .pattern = ":::1:::0:|:::1:1:0:",
        .haystack = ":::0:::1:::1:::0:",
        .expected = &[_]?Match{
            .{ .start = 8, .end = 17 },
        },
        .requires = caps.requires(.{ .alternation = true }),
    },
    .{
        .name = "basic56",
        .pattern = ":::1:::0:|:::1:1:1:",
        .haystack = ":::0:::1:::1:::0:",
        .expected = &[_]?Match{
            .{ .start = 8, .end = 17 },
        },
        .requires = caps.requires(.{ .alternation = true }),
    },
    .{
        .name = "basic57",
        .pattern = "[[:upper:]]",
        .haystack = "A",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .class_simple = true, .class_posix = true, .input_anchored = true }),
    },
    .{
        .name = "basic58",
        .pattern = "[[:lower:]]+",
        .haystack = "`az{",
        .expected = &[_]?Match{
            .{ .start = 1, .end = 3 },
        },
        .requires = caps.requires(.{ .rep_one_or_more = true, .class_simple = true, .class_posix = true }),
    },
    .{
        .name = "basic59",
        .pattern = "[[:upper:]]+",
        .haystack = "@AZ[",
        .expected = &[_]?Match{
            .{ .start = 1, .end = 3 },
        },
        .requires = caps.requires(.{ .rep_one_or_more = true, .class_simple = true, .class_posix = true }),
    },
    .{
        .name = "basic65",
        .pattern = "\\n",
        .haystack = "\\n",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .escape_c_style = true, .case_unescape = true, .input_anchored = true }),
    },
    .{
        .name = "basic66",
        .pattern = "\\n",
        .haystack = "\\n",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .escape_c_style = true, .case_unescape = true, .input_anchored = true }),
    },
    .{
        .name = "basic67",
        .pattern = "[^a]",
        .haystack = "\\n",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .class_simple = true, .class_negated = true, .case_unescape = true, .input_anchored = true }),
    },
    .{
        .name = "basic68",
        .pattern = "\\na",
        .haystack = "\\na",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
        },
        .requires = caps.requires(.{ .escape_c_style = true, .case_unescape = true, .input_anchored = true }),
    },
    .{
        .name = "basic69",
        .pattern = "(a)(b)(c)",
        .haystack = "abc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            .{ .start = 0, .end = 1 },
            .{ .start = 1, .end = 2 },
            .{ .start = 2, .end = 3 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    },
    .{
        .name = "basic70",
        .pattern = "xxx",
        .haystack = "xxx",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    },
    .{
        .name = "basic72",
        .pattern = "(?:^|[ (,;])(?:(?:(?:[Ff]eb[^ ]* *|0*2/|\\* */?)0*[6-7]))(?:[^0-9]|$)",
        .haystack = "feb 6,",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .alternation = true, .noncapture_group = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .class_simple = true, .class_range = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic74",
        .pattern = "(?:^|[ (,;])(?:(?:(?:[Ff]eb[^ ]* *|0*2/|\\* */?)0*[6-7]))(?:[^0-9]|$)",
        .haystack = "2/7",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .alternation = true, .noncapture_group = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .class_simple = true, .class_range = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic76",
        .pattern = "(?:^|[ (,;])(?:(?:(?:[Ff]eb[^ ]* *|0*2/|\\* */?)0*[6-7]))(?:[^0-9]|$)",
        .haystack = "feb 1,Feb 6",
        .expected = &[_]?Match{
            .{ .start = 5, .end = 11 },
        },
        .requires = caps.requires(.{ .alternation = true, .noncapture_group = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .class_simple = true, .class_range = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true }),
    },
    .{
        .name = "basic78",
        .pattern = "(((?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:x))))))))))))))))))))))))))))))",
        .haystack = "x",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .noncapture_group = true, .rep_zero_or_one = true, .input_anchored = true }),
    },
    .{
        .name = "basic80",
        .pattern = "(((?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:x))))))))))))))))))))))))))))))*",
        .haystack = "xx",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 1, .end = 2 },
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .noncapture_group = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic81",
        .pattern = "a?(ab|ba)*",
        .haystack = "ababababababababababababababababababababababababababababababababababababababababa",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 81 },
            .{ .start = 79, .end = 81 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic82",
        .pattern = "abaa|abbaa|abbbaa|abbbbaa",
        .haystack = "ababbabbbabbbabbbbabbbbaa",
        .expected = &[_]?Match{
            .{ .start = 18, .end = 25 },
        },
        .requires = caps.requires(.{ .alternation = true }),
    },
    .{
        .name = "basic83",
        .pattern = "abaa|abbaa|abbbaa|abbbbaa",
        .haystack = "ababbabbbabbbabbbbabaa",
        .expected = &[_]?Match{
            .{ .start = 18, .end = 22 },
        },
        .requires = caps.requires(.{ .alternation = true }),
    },
    .{
        .name = "basic84",
        .pattern = "aaac|aabc|abac|abbc|baac|babc|bbac|bbbc",
        .haystack = "baaabbbabac",
        .expected = &[_]?Match{
            .{ .start = 7, .end = 11 },
        },
        .requires = caps.requires(.{ .alternation = true }),
    },
    .{
        .name = "basic86",
        .pattern = ".*",
        .haystack = "\\x01\\x7f",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_more = true, .case_unescape = true, .input_anchored = true }),
    },
    .{
        .name = "basic87",
        .pattern = "aaaa|bbbb|cccc|ddddd|eeeeee|fffffff|gggg|hhhh|iiiii|jjjjj|kkkkk|llll",
        .haystack = "XaaaXbbbXcccXdddXeeeXfffXgggXhhhXiiiXjjjXkkkXlllXcbaXaaaa",
        .expected = &[_]?Match{
            .{ .start = 53, .end = 57 },
        },
        .requires = caps.requires(.{ .alternation = true }),
    },
    .{
        .name = "basic89",
        .pattern = "a*a*a*a*a*b",
        .haystack = "aaaaaaaaab",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 10 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic90",
        .pattern = "^",
        .haystack = "",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .anchor_line_start = true, .input_anchored = true }),
    },
    .{
        .name = "basic91",
        .pattern = "$",
        .haystack = "",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic92",
        .pattern = "^$",
        .haystack = "",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic93",
        .pattern = "^a$",
        .haystack = "a",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic94",
        .pattern = "abc",
        .haystack = "abc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    },
    .{
        .name = "basic95",
        .pattern = "abc",
        .haystack = "xabcy",
        .expected = &[_]?Match{
            .{ .start = 1, .end = 4 },
        },
    },
    .{
        .name = "basic96",
        .pattern = "abc",
        .haystack = "ababc",
        .expected = &[_]?Match{
            .{ .start = 2, .end = 5 },
        },
    },
    .{
        .name = "basic97",
        .pattern = "ab*c",
        .haystack = "abc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic98",
        .pattern = "ab*bc",
        .haystack = "abc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic99",
        .pattern = "ab*bc",
        .haystack = "abbc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic100",
        .pattern = "ab*bc",
        .haystack = "abbbbc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic101",
        .pattern = "ab+bc",
        .haystack = "abbc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
        },
        .requires = caps.requires(.{ .rep_one_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic102",
        .pattern = "ab+bc",
        .haystack = "abbbbc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_one_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic103",
        .pattern = "ab?bc",
        .haystack = "abbc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
        },
        .requires = caps.requires(.{ .rep_zero_or_one = true, .input_anchored = true }),
    },
    .{
        .name = "basic104",
        .pattern = "ab?bc",
        .haystack = "abc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .rep_zero_or_one = true, .input_anchored = true }),
    },
    .{
        .name = "basic105",
        .pattern = "ab?c",
        .haystack = "abc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .rep_zero_or_one = true, .input_anchored = true }),
    },
    .{
        .name = "basic106",
        .pattern = "^abc$",
        .haystack = "abc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic107",
        .pattern = "^abc",
        .haystack = "abcc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .anchor_line_start = true, .input_anchored = true }),
    },
    .{
        .name = "basic108",
        .pattern = "abc$",
        .haystack = "aabc",
        .expected = &[_]?Match{
            .{ .start = 1, .end = 4 },
        },
        .requires = caps.requires(.{ .anchor_line_end = true }),
    },
    .{
        .name = "basic109",
        .pattern = "^",
        .haystack = "abc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .anchor_line_start = true, .input_anchored = true }),
    },
    .{
        .name = "basic110",
        .pattern = "$",
        .haystack = "abc",
        .expected = &[_]?Match{
            .{ .start = 3, .end = 3 },
        },
        .requires = caps.requires(.{ .anchor_line_end = true }),
    },
    .{
        .name = "basic111",
        .pattern = "a.c",
        .haystack = "abc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .dot = true, .input_anchored = true }),
    },
    .{
        .name = "basic112",
        .pattern = "a.c",
        .haystack = "axc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .dot = true, .input_anchored = true }),
    },
    .{
        .name = "basic113",
        .pattern = "a.*c",
        .haystack = "axyzc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 5 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic114",
        .pattern = "a[bc]d",
        .haystack = "abd",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic115",
        .pattern = "a[b-d]e",
        .haystack = "ace",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .class_simple = true, .class_range = true, .input_anchored = true }),
    },
    .{
        .name = "basic116",
        .pattern = "a[b-d]",
        .haystack = "aac",
        .expected = &[_]?Match{
            .{ .start = 1, .end = 3 },
        },
        .requires = caps.requires(.{ .class_simple = true, .class_range = true }),
    },
    .{
        .name = "basic117",
        .pattern = "a[-b]",
        .haystack = "a-",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
        },
        .requires = caps.requires(.{ .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic118",
        .pattern = "a[b-]",
        .haystack = "a-",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
        },
        .requires = caps.requires(.{ .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic119",
        .pattern = "a]",
        .haystack = "a]",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    },
    .{
        .name = "basic120",
        .pattern = "a[]]b",
        .haystack = "a]b",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic121",
        .pattern = "a[^bc]d",
        .haystack = "aed",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .class_simple = true, .class_negated = true, .input_anchored = true }),
    },
    .{
        .name = "basic122",
        .pattern = "a[^-b]c",
        .haystack = "adc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .class_simple = true, .class_negated = true, .input_anchored = true }),
    },
    .{
        .name = "basic123",
        .pattern = "a[^]b]c",
        .haystack = "adc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .class_simple = true, .class_negated = true, .input_anchored = true }),
    },
    .{
        .name = "basic124",
        .pattern = "ab|cd",
        .haystack = "abc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    },
    .{
        .name = "basic125",
        .pattern = "ab|cd",
        .haystack = "abcd",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    },
    .{
        .name = "basic126",
        .pattern = "a\\(b",
        .haystack = "a(b",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    },
    .{
        .name = "basic127",
        .pattern = "a\\(*b",
        .haystack = "ab",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic128",
        .pattern = "a\\(*b",
        .haystack = "a((b",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic129",
        .pattern = "((a))",
        .haystack = "abc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    },
    .{
        .name = "basic130",
        .pattern = "(a)b(c)",
        .haystack = "abc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            .{ .start = 0, .end = 1 },
            .{ .start = 2, .end = 3 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    },
    .{
        .name = "basic131",
        .pattern = "a+b+c",
        .haystack = "aabbabc",
        .expected = &[_]?Match{
            .{ .start = 4, .end = 7 },
        },
        .requires = caps.requires(.{ .rep_one_or_more = true }),
    },
    .{
        .name = "basic132",
        .pattern = "a*",
        .haystack = "aaa",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic133",
        .pattern = "(a*)*",
        .haystack = "-",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic134",
        .pattern = "(a*)+",
        .haystack = "-",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic135",
        .pattern = "(a*|b)*",
        .haystack = "-",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic136",
        .pattern = "(a+|b)*",
        .haystack = "ab",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic137",
        .pattern = "(a+|b)+",
        .haystack = "ab",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_one_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic138",
        .pattern = "(a+|b)?",
        .haystack = "ab",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_one = true, .rep_one_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic139",
        .pattern = "[^ab]*",
        .haystack = "cde",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .class_negated = true, .input_anchored = true }),
    },
    .{
        .name = "basic140",
        .pattern = "(^)*",
        .haystack = "-",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .anchor_line_start = true, .input_anchored = true }),
    },
    .{
        .name = "basic141",
        .pattern = "a*",
        .haystack = "",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic142",
        .pattern = "([abc])*d",
        .haystack = "abbbcd",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 4, .end = 5 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic143",
        .pattern = "([abc])*bcd",
        .haystack = "abcd",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic144",
        .pattern = "a|b|c|d|e",
        .haystack = "e",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    },
    .{
        .name = "basic145",
        .pattern = "(a|b|c|d|e)f",
        .haystack = "ef",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    },
    .{
        .name = "basic146",
        .pattern = "((a*|b))*",
        .haystack = "-",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic147",
        .pattern = "abcd*efg",
        .haystack = "abcdefg",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic148",
        .pattern = "ab*",
        .haystack = "xabyabbbz",
        .expected = &[_]?Match{
            .{ .start = 1, .end = 3 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true }),
    },
    .{
        .name = "basic149",
        .pattern = "ab*",
        .haystack = "xayabbbz",
        .expected = &[_]?Match{
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true }),
    },
    .{
        .name = "basic150",
        .pattern = "(ab|cd)e",
        .haystack = "abcde",
        .expected = &[_]?Match{
            .{ .start = 2, .end = 5 },
            .{ .start = 2, .end = 4 },
        },
        .requires = caps.requires(.{ .alternation = true }),
    },
    .{
        .name = "basic151",
        .pattern = "[abhgefdc]ij",
        .haystack = "hij",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic152",
        .pattern = "(a|b)c*d",
        .haystack = "abcd",
        .expected = &[_]?Match{
            .{ .start = 1, .end = 4 },
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true }),
    },
    .{
        .name = "basic153",
        .pattern = "(ab|ab*)bc",
        .haystack = "abc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic154",
        .pattern = "a([bc]*)c*",
        .haystack = "abc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            .{ .start = 1, .end = 3 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic155",
        .pattern = "a([bc]*)(c*d)",
        .haystack = "abcd",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 1, .end = 3 },
            .{ .start = 3, .end = 4 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic156",
        .pattern = "a([bc]+)(c*d)",
        .haystack = "abcd",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 1, .end = 3 },
            .{ .start = 3, .end = 4 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic157",
        .pattern = "a([bc]*)(c+d)",
        .haystack = "abcd",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 1, .end = 2 },
            .{ .start = 2, .end = 4 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic158",
        .pattern = "a[bcd]*dcdcde",
        .haystack = "adcdcde",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic159",
        .pattern = "(ab|a)b*c",
        .haystack = "abc",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            .{ .start = 0, .end = 2 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic160",
        .pattern = "((a)(b)c)(d)",
        .haystack = "abcd",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 0, .end = 3 },
            .{ .start = 0, .end = 1 },
            .{ .start = 1, .end = 2 },
            .{ .start = 3, .end = 4 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    },
    .{
        .name = "basic161",
        .pattern = "[A-Za-z_][A-Za-z0-9_]*",
        .haystack = "alpha",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 5 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .class_range = true, .input_anchored = true }),
    },
    .{
        .name = "basic162",
        .pattern = "^a(bc+|b[eh])g|.h$",
        .haystack = "abh",
        .expected = &[_]?Match{
            .{ .start = 1, .end = 3 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_one_or_more = true, .class_simple = true, .anchor_line_start = true, .anchor_line_end = true }),
    },
    .{
        .name = "basic163",
        .pattern = "(bc+d$|ef*g.|h?i(j|k))",
        .haystack = "effgz",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 5 },
            .{ .start = 0, .end = 5 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic164",
        .pattern = "(bc+d$|ef*g.|h?i(j|k))",
        .haystack = "ij",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic165",
        .pattern = "(bc+d$|ef*g.|h?i(j|k))",
        .haystack = "reffgz",
        .expected = &[_]?Match{
            .{ .start = 1, .end = 6 },
            .{ .start = 1, .end = 6 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .anchor_line_end = true }),
    },
    .{
        .name = "basic166",
        .pattern = "(((((((((a)))))))))",
        .haystack = "a",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    },
    .{
        .name = "basic167",
        .pattern = "multiple words",
        .haystack = "multiple words yeah",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 14 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    },
    .{
        .name = "basic168",
        .pattern = "(.*)c(.*)",
        .haystack = "abcde",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 5 },
            .{ .start = 0, .end = 2 },
            .{ .start = 3, .end = 5 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic169",
        .pattern = "abcd",
        .haystack = "abcd",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    },
    .{
        .name = "basic170",
        .pattern = "a(bc)d",
        .haystack = "abcd",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 1, .end = 3 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    },
    .{
        .name = "basic171",
        .pattern = "a[\\x01-\\x03]?c",
        .haystack = "a\\x02c",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .rep_zero_or_one = true, .class_simple = true, .class_range = true, .escape_hex_byte = true, .case_unescape = true, .input_anchored = true }),
    },
    .{
        .name = "basic172",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Muammar Qaddafi",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 15 },
            null,
            .{ .start = 10, .end = 12 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic173",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Mo'ammar Gadhafi",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 16 },
            null,
            .{ .start = 11, .end = 13 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic174",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Muammar Kaddafi",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 15 },
            null,
            .{ .start = 10, .end = 12 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic175",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Muammar Qadhafi",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 15 },
            null,
            .{ .start = 10, .end = 12 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic176",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Muammar Gadafi",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 14 },
            null,
            .{ .start = 10, .end = 11 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic177",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Mu'ammar Qadafi",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 15 },
            null,
            .{ .start = 11, .end = 12 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic178",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Moamar Gaddafi",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 14 },
            null,
            .{ .start = 9, .end = 11 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic179",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Mu'ammar Qadhdhafi",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 18 },
            null,
            .{ .start = 13, .end = 15 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic180",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Muammar Khaddafi",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 16 },
            null,
            .{ .start = 11, .end = 13 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic181",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Muammar Ghaddafy",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 16 },
            null,
            .{ .start = 11, .end = 13 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic182",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Muammar Ghadafi",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 15 },
            null,
            .{ .start = 11, .end = 12 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic183",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Muammar Ghaddafi",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 16 },
            null,
            .{ .start = 11, .end = 13 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic184",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Muamar Kaddafi",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 14 },
            null,
            .{ .start = 9, .end = 11 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic185",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Muammar Quathafi",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 16 },
            null,
            .{ .start = 11, .end = 13 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic186",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Muammar Gheddafi",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 16 },
            null,
            .{ .start = 11, .end = 13 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic187",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Moammar Khadafy",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 15 },
            null,
            .{ .start = 11, .end = 12 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic188",
        .pattern = "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]",
        .haystack = "Moammar Qudhafi",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 15 },
            null,
            .{ .start = 10, .end = 12 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "basic189",
        .pattern = "a+(b|c)*d+",
        .haystack = "aabcdd",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 3, .end = 4 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic190",
        .pattern = "^.+$",
        .haystack = "vivi",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_one_or_more = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic191",
        .pattern = "^(.+)$",
        .haystack = "vivi",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 0, .end = 4 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_one_or_more = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic192",
        .pattern = "^([^!.]+).att.com!(.+)$",
        .haystack = "gryphon.att.com!eby",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 19 },
            .{ .start = 0, .end = 7 },
            .{ .start = 16, .end = 19 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic193",
        .pattern = "^([^!]+!)?([^!]+)$",
        .haystack = "bas",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            null,
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .rep_zero_or_one = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic194",
        .pattern = "^([^!]+!)?([^!]+)$",
        .haystack = "bar!bas",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 4 },
            .{ .start = 4, .end = 7 },
        },
        .requires = caps.requires(.{ .rep_zero_or_one = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic195",
        .pattern = "^([^!]+!)?([^!]+)$",
        .haystack = "foo!bas",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 4 },
            .{ .start = 4, .end = 7 },
        },
        .requires = caps.requires(.{ .rep_zero_or_one = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic196",
        .pattern = "^.+!([^!]+!)([^!]+)$",
        .haystack = "foo!bar!bas",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 11 },
            .{ .start = 4, .end = 8 },
            .{ .start = 8, .end = 11 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic197",
        .pattern = "((foo)|(bar))!bas",
        .haystack = "bar!bas",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 3 },
            null,
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    },
    .{
        .name = "basic198",
        .pattern = "((foo)|(bar))!bas",
        .haystack = "foo!bar!bas",
        .expected = &[_]?Match{
            .{ .start = 4, .end = 11 },
            .{ .start = 4, .end = 7 },
            null,
            .{ .start = 4, .end = 7 },
        },
        .requires = caps.requires(.{ .alternation = true }),
    },
    .{
        .name = "basic199",
        .pattern = "((foo)|(bar))!bas",
        .haystack = "foo!bas",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 3 },
            .{ .start = 0, .end = 3 },
            null,
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    },
    .{
        .name = "basic200",
        .pattern = "((foo)|bar)!bas",
        .haystack = "bar!bas",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 3 },
            null,
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    },
    .{
        .name = "basic201",
        .pattern = "((foo)|bar)!bas",
        .haystack = "foo!bar!bas",
        .expected = &[_]?Match{
            .{ .start = 4, .end = 11 },
            .{ .start = 4, .end = 7 },
            null,
        },
        .requires = caps.requires(.{ .alternation = true }),
    },
    .{
        .name = "basic202",
        .pattern = "((foo)|bar)!bas",
        .haystack = "foo!bas",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 3 },
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    },
    .{
        .name = "basic203",
        .pattern = "(foo|(bar))!bas",
        .haystack = "bar!bas",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 3 },
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    },
    .{
        .name = "basic204",
        .pattern = "(foo|(bar))!bas",
        .haystack = "foo!bar!bas",
        .expected = &[_]?Match{
            .{ .start = 4, .end = 11 },
            .{ .start = 4, .end = 7 },
            .{ .start = 4, .end = 7 },
        },
        .requires = caps.requires(.{ .alternation = true }),
    },
    .{
        .name = "basic205",
        .pattern = "(foo|(bar))!bas",
        .haystack = "foo!bas",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 3 },
            null,
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    },
    .{
        .name = "basic206",
        .pattern = "(foo|bar)!bas",
        .haystack = "bar!bas",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    },
    .{
        .name = "basic207",
        .pattern = "(foo|bar)!bas",
        .haystack = "foo!bar!bas",
        .expected = &[_]?Match{
            .{ .start = 4, .end = 11 },
            .{ .start = 4, .end = 7 },
        },
        .requires = caps.requires(.{ .alternation = true }),
    },
    .{
        .name = "basic208",
        .pattern = "(foo|bar)!bas",
        .haystack = "foo!bas",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 3 },
        },
        .requires = caps.requires(.{ .alternation = true, .input_anchored = true }),
    },
    .{
        .name = "basic209",
        .pattern = "^(([^!]+!)?([^!]+)|.+!([^!]+!)([^!]+))$",
        .haystack = "foo!bar!bas",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 11 },
            .{ .start = 0, .end = 11 },
            null,
            null,
            .{ .start = 4, .end = 8 },
            .{ .start = 8, .end = 11 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic210",
        .pattern = "^([^!]+!)?([^!]+)$|^.+!([^!]+!)([^!]+)$",
        .haystack = "bas",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            null,
            .{ .start = 0, .end = 3 },
            null,
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic211",
        .pattern = "^([^!]+!)?([^!]+)$|^.+!([^!]+!)([^!]+)$",
        .haystack = "bar!bas",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 4 },
            .{ .start = 4, .end = 7 },
            null,
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic212",
        .pattern = "^([^!]+!)?([^!]+)$|^.+!([^!]+!)([^!]+)$",
        .haystack = "foo!bar!bas",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 11 },
            null,
            null,
            .{ .start = 4, .end = 8 },
            .{ .start = 8, .end = 11 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic213",
        .pattern = "^([^!]+!)?([^!]+)$|^.+!([^!]+!)([^!]+)$",
        .haystack = "foo!bas",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 4 },
            .{ .start = 4, .end = 7 },
            null,
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic214",
        .pattern = "^(([^!]+!)?([^!]+)|.+!([^!]+!)([^!]+))$",
        .haystack = "bas",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            .{ .start = 0, .end = 3 },
            null,
            .{ .start = 0, .end = 3 },
            null,
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic215",
        .pattern = "^(([^!]+!)?([^!]+)|.+!([^!]+!)([^!]+))$",
        .haystack = "bar!bas",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 4 },
            .{ .start = 4, .end = 7 },
            null,
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic216",
        .pattern = "^(([^!]+!)?([^!]+)|.+!([^!]+!)([^!]+))$",
        .haystack = "foo!bar!bas",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 11 },
            .{ .start = 0, .end = 11 },
            null,
            null,
            .{ .start = 4, .end = 8 },
            .{ .start = 8, .end = 11 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic217",
        .pattern = "^(([^!]+!)?([^!]+)|.+!([^!]+!)([^!]+))$",
        .haystack = "foo!bas",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 7 },
            .{ .start = 0, .end = 4 },
            .{ .start = 4, .end = 7 },
            null,
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_one = true, .rep_one_or_more = true, .class_simple = true, .class_negated = true, .anchor_line_start = true, .anchor_line_end = true, .input_anchored = true }),
    },
    .{
        .name = "basic218",
        .pattern = ".*(/XXX).*",
        .haystack = "/XXX",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 0, .end = 4 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic219",
        .pattern = ".*(\\\\XXX).*",
        .haystack = "\\XXX",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 0, .end = 4 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic220",
        .pattern = "\\\\XXX",
        .haystack = "\\XXX",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    },
    .{
        .name = "basic221",
        .pattern = ".*(/000).*",
        .haystack = "/000",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 0, .end = 4 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic222",
        .pattern = ".*(\\\\000).*",
        .haystack = "\\000",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 0, .end = 4 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "basic223",
        .pattern = "\\\\000",
        .haystack = "\\000",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
        },
        .requires = caps.requires(.{ .input_anchored = true }),
    },
};
