const harness = @import("../harness.zig");

pub const suite: harness.Suite = .{
    .name = "fowler/nullsubexpr",
    .cases = &cases,
};

const cases = [_]harness.Case{
    .{
        .name = "nullsubexpr3",
        .pattern = "(a*)*",
        .haystack = "a",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 } }),
    },
    .{
        .name = "nullsubexpr4",
        .pattern = "(a*)*",
        .haystack = "x",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 0 }, .{ 0, 0 } }),
    },
    .{
        .name = "nullsubexpr5",
        .pattern = "(a*)*",
        .haystack = "aaaaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 0, 6 } }),
    },
    .{
        .name = "nullsubexpr6",
        .pattern = "(a*)*",
        .haystack = "aaaaaax",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 0, 6 } }),
    },
    .{
        .name = "nullsubexpr7",
        .pattern = "(a*)+",
        .haystack = "a",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 } }),
    },
    .{
        .name = "nullsubexpr8",
        .pattern = "(a*)+",
        .haystack = "x",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 0 }, .{ 0, 0 } }),
    },
    .{
        .name = "nullsubexpr9",
        .pattern = "(a*)+",
        .haystack = "aaaaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 0, 6 } }),
    },
    .{
        .name = "nullsubexpr10",
        .pattern = "(a*)+",
        .haystack = "aaaaaax",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 0, 6 } }),
    },
    .{
        .name = "nullsubexpr11",
        .pattern = "(a+)*",
        .haystack = "a",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 } }),
    },
    .{
        .name = "nullsubexpr12",
        .pattern = "(a+)*",
        .haystack = "x",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 0 }, null }),
    },
    .{
        .name = "nullsubexpr13",
        .pattern = "(a+)*",
        .haystack = "aaaaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 0, 6 } }),
    },
    .{
        .name = "nullsubexpr14",
        .pattern = "(a+)*",
        .haystack = "aaaaaax",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 0, 6 } }),
    },
    .{
        .name = "nullsubexpr15",
        .pattern = "(a+)+",
        .haystack = "a",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 } }),
    },
    .{
        .name = "nullsubexpr16",
        .pattern = "(a+)+",
        .haystack = "x",
        .expected = .one(null),
    },
    .{
        .name = "nullsubexpr17",
        .pattern = "(a+)+",
        .haystack = "aaaaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 0, 6 } }),
    },
    .{
        .name = "nullsubexpr18",
        .pattern = "(a+)+",
        .haystack = "aaaaaax",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 0, 6 } }),
    },
    .{
        .name = "nullsubexpr20",
        .pattern = "([a]*)*",
        .haystack = "a",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 } }),
    },
    .{
        .name = "nullsubexpr21",
        .pattern = "([a]*)*",
        .haystack = "x",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 0 }, .{ 0, 0 } }),
    },
    .{
        .name = "nullsubexpr22",
        .pattern = "([a]*)*",
        .haystack = "aaaaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 0, 6 } }),
    },
    .{
        .name = "nullsubexpr23",
        .pattern = "([a]*)*",
        .haystack = "aaaaaax",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 0, 6 } }),
    },
    .{
        .name = "nullsubexpr24",
        .pattern = "([a]*)+",
        .haystack = "a",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 } }),
    },
    .{
        .name = "nullsubexpr25",
        .pattern = "([a]*)+",
        .haystack = "x",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 0 }, .{ 0, 0 } }),
    },
    .{
        .name = "nullsubexpr26",
        .pattern = "([a]*)+",
        .haystack = "aaaaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 0, 6 } }),
    },
    .{
        .name = "nullsubexpr27",
        .pattern = "([a]*)+",
        .haystack = "aaaaaax",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 0, 6 } }),
    },
    .{
        .name = "nullsubexpr28",
        .pattern = "([^b]*)*",
        .haystack = "a",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 } }),
    },
    .{
        .name = "nullsubexpr29",
        .pattern = "([^b]*)*",
        .haystack = "b",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 0 }, .{ 0, 0 } }),
    },
    .{
        .name = "nullsubexpr30",
        .pattern = "([^b]*)*",
        .haystack = "aaaaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 0, 6 } }),
    },
    .{
        .name = "nullsubexpr31",
        .pattern = "([^b]*)*",
        .haystack = "aaaaaab",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 0, 6 } }),
    },
    .{
        .name = "nullsubexpr32",
        .pattern = "([ab]*)*",
        .haystack = "a",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 } }),
    },
    .{
        .name = "nullsubexpr33",
        .pattern = "([ab]*)*",
        .haystack = "aaaaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 0, 6 } }),
    },
    .{
        .name = "nullsubexpr34",
        .pattern = "([ab]*)*",
        .haystack = "ababab",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 0, 6 } }),
    },
    .{
        .name = "nullsubexpr35",
        .pattern = "([ab]*)*",
        .haystack = "bababa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 0, 6 } }),
    },
    .{
        .name = "nullsubexpr36",
        .pattern = "([ab]*)*",
        .haystack = "b",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 } }),
    },
    .{
        .name = "nullsubexpr37",
        .pattern = "([ab]*)*",
        .haystack = "bbbbbb",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 0, 6 } }),
    },
    .{
        .name = "nullsubexpr38",
        .pattern = "([ab]*)*",
        .haystack = "aaaabcde",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 5 }, .{ 0, 5 } }),
    },
    .{
        .name = "nullsubexpr39",
        .pattern = "([^a]*)*",
        .haystack = "b",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 } }),
    },
    .{
        .name = "nullsubexpr40",
        .pattern = "([^a]*)*",
        .haystack = "bbbbbb",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 0, 6 } }),
    },
    .{
        .name = "nullsubexpr41",
        .pattern = "([^a]*)*",
        .haystack = "aaaaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 0 }, .{ 0, 0 } }),
    },
    .{
        .name = "nullsubexpr42",
        .pattern = "([^ab]*)*",
        .haystack = "ccccxx",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 0, 6 } }),
    },
    .{
        .name = "nullsubexpr43",
        .pattern = "([^ab]*)*",
        .haystack = "ababab",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 0 }, .{ 0, 0 } }),
    },
    .{
        .name = "nullsubexpr46",
        .pattern = "((z)+|a)*",
        .haystack = "zabcde",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 1, 2 }, .{ 0, 1 } }),
    },
    .{
        .name = "nullsubexpr64",
        .pattern = "(a*)*(x)",
        .haystack = "x",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 0 }, .{ 0, 1 } }),
    },
    .{
        .name = "nullsubexpr65",
        .pattern = "(a*)*(x)",
        .haystack = "ax",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 0, 1 }, .{ 1, 2 } }),
    },
    .{
        .name = "nullsubexpr66",
        .pattern = "(a*)*(x)",
        .haystack = "axa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 0, 1 }, .{ 1, 2 } }),
    },
    .{
        .name = "nullsubexpr68",
        .pattern = "(a*)+(x)",
        .haystack = "x",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 0 }, .{ 0, 1 } }),
    },
    .{
        .name = "nullsubexpr69",
        .pattern = "(a*)+(x)",
        .haystack = "ax",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 0, 1 }, .{ 1, 2 } }),
    },
    .{
        .name = "nullsubexpr70",
        .pattern = "(a*)+(x)",
        .haystack = "axa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 0, 1 }, .{ 1, 2 } }),
    },
    .{
        .name = "nullsubexpr72",
        .pattern = "(a*){2}(x)",
        .haystack = "x",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 0 }, .{ 0, 1 } }),
    },
    .{
        .name = "nullsubexpr73",
        .pattern = "(a*){2}(x)",
        .haystack = "ax",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 1, 1 }, .{ 1, 2 } }),
    },
    .{
        .name = "nullsubexpr74",
        .pattern = "(a*){2}(x)",
        .haystack = "axa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 1, 1 }, .{ 1, 2 } }),
    },
};
