//! GENERATED by `zig build gen-tests -- fowler`.
//! Source: tests/fowler/data/nullsubexpr.toml
//! DO NOT EDIT.

const std = @import("std");
const gpa = std.testing.allocator;
const harness = @import("../harness.zig");
const exec = harness.execute;
const caps = harness.capabilities;
const root = @import("root");
const Match = @import("export_test").Regex.Match;

fn config() exec.Options {
    return .{ .verbose = root.verbose, .trace = root.trace };
}

fn executeCase(tc: exec.Case) !void {
    try exec.execute(gpa, tc, .pikevm, config());
}

test "fowler/nullsubexpr/nullsubexpr3" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr3",
        .pattern = "(a*)*",
        .input = .{ .haystack = "a", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr4" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr4",
        .pattern = "(a*)*",
        .input = .{ .haystack = "x", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr5" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr5",
        .pattern = "(a*)*",
        .input = .{ .haystack = "aaaaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr6" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr6",
        .pattern = "(a*)*",
        .input = .{ .haystack = "aaaaaax", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr7" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr7",
        .pattern = "(a*)+",
        .input = .{ .haystack = "a", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr8" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr8",
        .pattern = "(a*)+",
        .input = .{ .haystack = "x", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr9" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr9",
        .pattern = "(a*)+",
        .input = .{ .haystack = "aaaaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr10" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr10",
        .pattern = "(a*)+",
        .input = .{ .haystack = "aaaaaax", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr11" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr11",
        .pattern = "(a+)*",
        .input = .{ .haystack = "a", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr12" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr12",
        .pattern = "(a+)*",
        .input = .{ .haystack = "x", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            null,
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr13" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr13",
        .pattern = "(a+)*",
        .input = .{ .haystack = "aaaaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr14" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr14",
        .pattern = "(a+)*",
        .input = .{ .haystack = "aaaaaax", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr15" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr15",
        .pattern = "(a+)+",
        .input = .{ .haystack = "a", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_one_or_more = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr16" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr16",
        .pattern = "(a+)+",
        .input = .{ .haystack = "x", .anchored = false },
        .expected = &[_]?Match{},
        .requires = caps.requires(.{ .rep_one_or_more = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr17" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr17",
        .pattern = "(a+)+",
        .input = .{ .haystack = "aaaaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_one_or_more = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr18" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr18",
        .pattern = "(a+)+",
        .input = .{ .haystack = "aaaaaax", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_one_or_more = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr20" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr20",
        .pattern = "([a]*)*",
        .input = .{ .haystack = "a", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr21" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr21",
        .pattern = "([a]*)*",
        .input = .{ .haystack = "x", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr22" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr22",
        .pattern = "([a]*)*",
        .input = .{ .haystack = "aaaaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr23" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr23",
        .pattern = "([a]*)*",
        .input = .{ .haystack = "aaaaaax", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr24" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr24",
        .pattern = "([a]*)+",
        .input = .{ .haystack = "a", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr25" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr25",
        .pattern = "([a]*)+",
        .input = .{ .haystack = "x", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr26" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr26",
        .pattern = "([a]*)+",
        .input = .{ .haystack = "aaaaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr27" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr27",
        .pattern = "([a]*)+",
        .input = .{ .haystack = "aaaaaax", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr28" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr28",
        .pattern = "([^b]*)*",
        .input = .{ .haystack = "a", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .class_negated = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr29" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr29",
        .pattern = "([^b]*)*",
        .input = .{ .haystack = "b", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .class_negated = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr30" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr30",
        .pattern = "([^b]*)*",
        .input = .{ .haystack = "aaaaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .class_negated = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr31" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr31",
        .pattern = "([^b]*)*",
        .input = .{ .haystack = "aaaaaab", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .class_negated = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr32" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr32",
        .pattern = "([ab]*)*",
        .input = .{ .haystack = "a", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr33" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr33",
        .pattern = "([ab]*)*",
        .input = .{ .haystack = "aaaaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr34" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr34",
        .pattern = "([ab]*)*",
        .input = .{ .haystack = "ababab", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr35" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr35",
        .pattern = "([ab]*)*",
        .input = .{ .haystack = "bababa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr36" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr36",
        .pattern = "([ab]*)*",
        .input = .{ .haystack = "b", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr37" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr37",
        .pattern = "([ab]*)*",
        .input = .{ .haystack = "bbbbbb", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr38" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr38",
        .pattern = "([ab]*)*",
        .input = .{ .haystack = "aaaabcde", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 5 },
            .{ .start = 0, .end = 5 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr39" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr39",
        .pattern = "([^a]*)*",
        .input = .{ .haystack = "b", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .class_negated = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr40" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr40",
        .pattern = "([^a]*)*",
        .input = .{ .haystack = "bbbbbb", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .class_negated = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr41" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr41",
        .pattern = "([^a]*)*",
        .input = .{ .haystack = "aaaaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .class_negated = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr42" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr42",
        .pattern = "([^ab]*)*",
        .input = .{ .haystack = "ccccxx", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .class_negated = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr43" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr43",
        .pattern = "([^ab]*)*",
        .input = .{ .haystack = "ababab", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .class_negated = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr46" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr46",
        .pattern = "((z)+|a)*",
        .input = .{ .haystack = "zabcde", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 1, .end = 2 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr64" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr64",
        .pattern = "(a*)*(x)",
        .input = .{ .haystack = "x", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr65" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr65",
        .pattern = "(a*)*(x)",
        .input = .{ .haystack = "ax", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 1 },
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr66" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr66",
        .pattern = "(a*)*(x)",
        .input = .{ .haystack = "axa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 1 },
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr68" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr68",
        .pattern = "(a*)+(x)",
        .input = .{ .haystack = "x", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr69" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr69",
        .pattern = "(a*)+(x)",
        .input = .{ .haystack = "ax", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 1 },
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr70" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr70",
        .pattern = "(a*)+(x)",
        .input = .{ .haystack = "axa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 1 },
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr72" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr72",
        .pattern = "(a*){2}(x)",
        .input = .{ .haystack = "x", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_exact = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr73" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr73",
        .pattern = "(a*){2}(x)",
        .input = .{ .haystack = "ax", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 1, .end = 1 },
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_exact = true, .input_anchored = true }),
    });
}

test "fowler/nullsubexpr/nullsubexpr74" {
    try executeCase(.{
        .name = "fowler/nullsubexpr/nullsubexpr74",
        .pattern = "(a*){2}(x)",
        .input = .{ .haystack = "axa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 1, .end = 1 },
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_exact = true, .input_anchored = true }),
    });
}
