//! GENERATED by `zig build gen-tests -- fowler`.
//! Source: tests/fowler/data/nullsubexpr.toml
//! DO NOT EDIT.

const harness = @import("../harness.zig");
const runner = harness.runner;
const caps = harness.capabilities;
const Match = @import("export_test").Regex.Match;

pub const cases = [_]runner.Case{
    .{
        .name = "nullsubexpr3",
        .pattern = "(a*)*",
        .haystack = "a",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr4",
        .pattern = "(a*)*",
        .haystack = "x",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr5",
        .pattern = "(a*)*",
        .haystack = "aaaaaa",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr6",
        .pattern = "(a*)*",
        .haystack = "aaaaaax",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr7",
        .pattern = "(a*)+",
        .haystack = "a",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr8",
        .pattern = "(a*)+",
        .haystack = "x",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr9",
        .pattern = "(a*)+",
        .haystack = "aaaaaa",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr10",
        .pattern = "(a*)+",
        .haystack = "aaaaaax",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr11",
        .pattern = "(a+)*",
        .haystack = "a",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr12",
        .pattern = "(a+)*",
        .haystack = "x",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            null,
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr13",
        .pattern = "(a+)*",
        .haystack = "aaaaaa",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr14",
        .pattern = "(a+)*",
        .haystack = "aaaaaax",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr15",
        .pattern = "(a+)+",
        .haystack = "a",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_one_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr16",
        .pattern = "(a+)+",
        .haystack = "x",
        .expected = &[_]?Match{},
        .requires = caps.requires(.{ .rep_one_or_more = true }),
    },
    .{
        .name = "nullsubexpr17",
        .pattern = "(a+)+",
        .haystack = "aaaaaa",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_one_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr18",
        .pattern = "(a+)+",
        .haystack = "aaaaaax",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_one_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr20",
        .pattern = "([a]*)*",
        .haystack = "a",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr21",
        .pattern = "([a]*)*",
        .haystack = "x",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr22",
        .pattern = "([a]*)*",
        .haystack = "aaaaaa",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr23",
        .pattern = "([a]*)*",
        .haystack = "aaaaaax",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr24",
        .pattern = "([a]*)+",
        .haystack = "a",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr25",
        .pattern = "([a]*)+",
        .haystack = "x",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr26",
        .pattern = "([a]*)+",
        .haystack = "aaaaaa",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr27",
        .pattern = "([a]*)+",
        .haystack = "aaaaaax",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr28",
        .pattern = "([^b]*)*",
        .haystack = "a",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .class_negated = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr29",
        .pattern = "([^b]*)*",
        .haystack = "b",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .class_negated = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr30",
        .pattern = "([^b]*)*",
        .haystack = "aaaaaa",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .class_negated = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr31",
        .pattern = "([^b]*)*",
        .haystack = "aaaaaab",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .class_negated = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr32",
        .pattern = "([ab]*)*",
        .haystack = "a",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr33",
        .pattern = "([ab]*)*",
        .haystack = "aaaaaa",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr34",
        .pattern = "([ab]*)*",
        .haystack = "ababab",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr35",
        .pattern = "([ab]*)*",
        .haystack = "bababa",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr36",
        .pattern = "([ab]*)*",
        .haystack = "b",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr37",
        .pattern = "([ab]*)*",
        .haystack = "bbbbbb",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr38",
        .pattern = "([ab]*)*",
        .haystack = "aaaabcde",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 5 },
            .{ .start = 0, .end = 5 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr39",
        .pattern = "([^a]*)*",
        .haystack = "b",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .class_negated = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr40",
        .pattern = "([^a]*)*",
        .haystack = "bbbbbb",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .class_negated = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr41",
        .pattern = "([^a]*)*",
        .haystack = "aaaaaa",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .class_negated = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr42",
        .pattern = "([^ab]*)*",
        .haystack = "ccccxx",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 6 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .class_negated = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr43",
        .pattern = "([^ab]*)*",
        .haystack = "ababab",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 0 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .class_simple = true, .class_negated = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr46",
        .pattern = "((z)+|a)*",
        .haystack = "zabcde",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 1, .end = 2 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr64",
        .pattern = "(a*)*(x)",
        .haystack = "x",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr65",
        .pattern = "(a*)*(x)",
        .haystack = "ax",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 1 },
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr66",
        .pattern = "(a*)*(x)",
        .haystack = "axa",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 1 },
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr68",
        .pattern = "(a*)+(x)",
        .haystack = "x",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr69",
        .pattern = "(a*)+(x)",
        .haystack = "ax",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 1 },
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr70",
        .pattern = "(a*)+(x)",
        .haystack = "axa",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 1 },
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr72",
        .pattern = "(a*){2}(x)",
        .haystack = "x",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 0 },
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_exact = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr73",
        .pattern = "(a*){2}(x)",
        .haystack = "ax",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 1, .end = 1 },
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_exact = true, .input_anchored = true }),
    },
    .{
        .name = "nullsubexpr74",
        .pattern = "(a*){2}(x)",
        .haystack = "axa",
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 1, .end = 1 },
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .rep_zero_or_more = true, .rep_exact = true, .input_anchored = true }),
    },
};
