//! GENERATED by `zig build gen-tests -- fowler`.
//! Source: tests/fowler/data/repetition.toml
//! DO NOT EDIT.

const std = @import("std");
const gpa = std.testing.allocator;
const harness = @import("../harness.zig");
const exec = harness.execute;
const caps = harness.capabilities;
const root = @import("root");
const Match = @import("export_test").Regex.Match;

fn config() exec.Options {
    return .{ .verbose = root.verbose, .trace = root.trace };
}

fn executeCase(tc: exec.Case) !void {
    try exec.execute(gpa, tc, .pikevm, config());
}

test "fowler/repetition/repetition10" {
    try executeCase(.{
        .name = "fowler/repetition/repetition10",
        .pattern = "((..)|(.))",
        .input = .{ .haystack = "", .anchored = false },
        .expected = &[_]?Match{},
        .requires = caps.requires(.{ .dot = true, .alternation = true }),
    });
}

test "fowler/repetition/repetition11" {
    try executeCase(.{
        .name = "fowler/repetition/repetition11",
        .pattern = "((..)|(.))((..)|(.))",
        .input = .{ .haystack = "", .anchored = false },
        .expected = &[_]?Match{},
        .requires = caps.requires(.{ .dot = true, .alternation = true }),
    });
}

test "fowler/repetition/repetition12" {
    try executeCase(.{
        .name = "fowler/repetition/repetition12",
        .pattern = "((..)|(.))((..)|(.))((..)|(.))",
        .input = .{ .haystack = "", .anchored = false },
        .expected = &[_]?Match{},
        .requires = caps.requires(.{ .dot = true, .alternation = true }),
    });
}

test "fowler/repetition/repetition14" {
    try executeCase(.{
        .name = "fowler/repetition/repetition14",
        .pattern = "((..)|(.)){1}",
        .input = .{ .haystack = "", .anchored = false },
        .expected = &[_]?Match{},
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_exact = true }),
    });
}

test "fowler/repetition/repetition15" {
    try executeCase(.{
        .name = "fowler/repetition/repetition15",
        .pattern = "((..)|(.)){2}",
        .input = .{ .haystack = "", .anchored = false },
        .expected = &[_]?Match{},
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_exact = true }),
    });
}

test "fowler/repetition/repetition16" {
    try executeCase(.{
        .name = "fowler/repetition/repetition16",
        .pattern = "((..)|(.)){3}",
        .input = .{ .haystack = "", .anchored = false },
        .expected = &[_]?Match{},
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_exact = true }),
    });
}

test "fowler/repetition/repetition18" {
    try executeCase(.{
        .name = "fowler/repetition/repetition18",
        .pattern = "((..)|(.))*",
        .input = .{ .haystack = "", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 0 },
            null,
            null,
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition20" {
    try executeCase(.{
        .name = "fowler/repetition/repetition20",
        .pattern = "((..)|(.))",
        .input = .{ .haystack = "a", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            null,
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition21" {
    try executeCase(.{
        .name = "fowler/repetition/repetition21",
        .pattern = "((..)|(.))((..)|(.))",
        .input = .{ .haystack = "a", .anchored = false },
        .expected = &[_]?Match{},
        .requires = caps.requires(.{ .dot = true, .alternation = true }),
    });
}

test "fowler/repetition/repetition22" {
    try executeCase(.{
        .name = "fowler/repetition/repetition22",
        .pattern = "((..)|(.))((..)|(.))((..)|(.))",
        .input = .{ .haystack = "a", .anchored = false },
        .expected = &[_]?Match{},
        .requires = caps.requires(.{ .dot = true, .alternation = true }),
    });
}

test "fowler/repetition/repetition24" {
    try executeCase(.{
        .name = "fowler/repetition/repetition24",
        .pattern = "((..)|(.)){1}",
        .input = .{ .haystack = "a", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            null,
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_exact = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition25" {
    try executeCase(.{
        .name = "fowler/repetition/repetition25",
        .pattern = "((..)|(.)){2}",
        .input = .{ .haystack = "a", .anchored = false },
        .expected = &[_]?Match{},
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_exact = true }),
    });
}

test "fowler/repetition/repetition26" {
    try executeCase(.{
        .name = "fowler/repetition/repetition26",
        .pattern = "((..)|(.)){3}",
        .input = .{ .haystack = "a", .anchored = false },
        .expected = &[_]?Match{},
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_exact = true }),
    });
}

test "fowler/repetition/repetition28" {
    try executeCase(.{
        .name = "fowler/repetition/repetition28",
        .pattern = "((..)|(.))*",
        .input = .{ .haystack = "a", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            null,
            .{ .start = 0, .end = 1 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition30" {
    try executeCase(.{
        .name = "fowler/repetition/repetition30",
        .pattern = "((..)|(.))",
        .input = .{ .haystack = "aa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition31" {
    try executeCase(.{
        .name = "fowler/repetition/repetition31",
        .pattern = "((..)|(.))((..)|(.))",
        .input = .{ .haystack = "aa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 1 },
            null,
            .{ .start = 0, .end = 1 },
            .{ .start = 1, .end = 2 },
            null,
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition32" {
    try executeCase(.{
        .name = "fowler/repetition/repetition32",
        .pattern = "((..)|(.))((..)|(.))((..)|(.))",
        .input = .{ .haystack = "aa", .anchored = false },
        .expected = &[_]?Match{},
        .requires = caps.requires(.{ .dot = true, .alternation = true }),
    });
}

test "fowler/repetition/repetition34" {
    try executeCase(.{
        .name = "fowler/repetition/repetition34",
        .pattern = "((..)|(.)){1}",
        .input = .{ .haystack = "aa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_exact = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition35" {
    try executeCase(.{
        .name = "fowler/repetition/repetition35",
        .pattern = "((..)|(.)){2}",
        .input = .{ .haystack = "aa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 1, .end = 2 },
            null,
            .{ .start = 1, .end = 2 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_exact = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition36" {
    try executeCase(.{
        .name = "fowler/repetition/repetition36",
        .pattern = "((..)|(.)){3}",
        .input = .{ .haystack = "aa", .anchored = false },
        .expected = &[_]?Match{},
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_exact = true }),
    });
}

test "fowler/repetition/repetition38" {
    try executeCase(.{
        .name = "fowler/repetition/repetition38",
        .pattern = "((..)|(.))*",
        .input = .{ .haystack = "aa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition40" {
    try executeCase(.{
        .name = "fowler/repetition/repetition40",
        .pattern = "((..)|(.))",
        .input = .{ .haystack = "aaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition41" {
    try executeCase(.{
        .name = "fowler/repetition/repetition41",
        .pattern = "((..)|(.))((..)|(.))",
        .input = .{ .haystack = "aaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            null,
            .{ .start = 2, .end = 3 },
            null,
            .{ .start = 2, .end = 3 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition42" {
    try executeCase(.{
        .name = "fowler/repetition/repetition42",
        .pattern = "((..)|(.))((..)|(.))((..)|(.))",
        .input = .{ .haystack = "aaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            .{ .start = 0, .end = 1 },
            null,
            .{ .start = 0, .end = 1 },
            .{ .start = 1, .end = 2 },
            null,
            .{ .start = 1, .end = 2 },
            .{ .start = 2, .end = 3 },
            null,
            .{ .start = 2, .end = 3 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition44" {
    try executeCase(.{
        .name = "fowler/repetition/repetition44",
        .pattern = "((..)|(.)){1}",
        .input = .{ .haystack = "aaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_exact = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition46" {
    try executeCase(.{
        .name = "fowler/repetition/repetition46",
        .pattern = "((..)|(.)){2}",
        .input = .{ .haystack = "aaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            .{ .start = 2, .end = 3 },
            .{ .start = 0, .end = 2 },
            .{ .start = 2, .end = 3 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_exact = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition47" {
    try executeCase(.{
        .name = "fowler/repetition/repetition47",
        .pattern = "((..)|(.)){3}",
        .input = .{ .haystack = "aaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            .{ .start = 2, .end = 3 },
            null,
            .{ .start = 2, .end = 3 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_exact = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition50" {
    try executeCase(.{
        .name = "fowler/repetition/repetition50",
        .pattern = "((..)|(.))*",
        .input = .{ .haystack = "aaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 3 },
            .{ .start = 2, .end = 3 },
            .{ .start = 0, .end = 2 },
            .{ .start = 2, .end = 3 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition52" {
    try executeCase(.{
        .name = "fowler/repetition/repetition52",
        .pattern = "((..)|(.))",
        .input = .{ .haystack = "aaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition53" {
    try executeCase(.{
        .name = "fowler/repetition/repetition53",
        .pattern = "((..)|(.))((..)|(.))",
        .input = .{ .haystack = "aaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            null,
            .{ .start = 2, .end = 4 },
            .{ .start = 2, .end = 4 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition54" {
    try executeCase(.{
        .name = "fowler/repetition/repetition54",
        .pattern = "((..)|(.))((..)|(.))((..)|(.))",
        .input = .{ .haystack = "aaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            null,
            .{ .start = 2, .end = 3 },
            null,
            .{ .start = 2, .end = 3 },
            .{ .start = 3, .end = 4 },
            null,
            .{ .start = 3, .end = 4 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition56" {
    try executeCase(.{
        .name = "fowler/repetition/repetition56",
        .pattern = "((..)|(.)){1}",
        .input = .{ .haystack = "aaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_exact = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition57" {
    try executeCase(.{
        .name = "fowler/repetition/repetition57",
        .pattern = "((..)|(.)){2}",
        .input = .{ .haystack = "aaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 2, .end = 4 },
            .{ .start = 2, .end = 4 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_exact = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition59" {
    try executeCase(.{
        .name = "fowler/repetition/repetition59",
        .pattern = "((..)|(.)){3}",
        .input = .{ .haystack = "aaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 3, .end = 4 },
            .{ .start = 0, .end = 2 },
            .{ .start = 3, .end = 4 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_exact = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition61" {
    try executeCase(.{
        .name = "fowler/repetition/repetition61",
        .pattern = "((..)|(.))*",
        .input = .{ .haystack = "aaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 2, .end = 4 },
            .{ .start = 2, .end = 4 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition63" {
    try executeCase(.{
        .name = "fowler/repetition/repetition63",
        .pattern = "((..)|(.))",
        .input = .{ .haystack = "aaaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition64" {
    try executeCase(.{
        .name = "fowler/repetition/repetition64",
        .pattern = "((..)|(.))((..)|(.))",
        .input = .{ .haystack = "aaaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            null,
            .{ .start = 2, .end = 4 },
            .{ .start = 2, .end = 4 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition65" {
    try executeCase(.{
        .name = "fowler/repetition/repetition65",
        .pattern = "((..)|(.))((..)|(.))((..)|(.))",
        .input = .{ .haystack = "aaaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 5 },
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            null,
            .{ .start = 2, .end = 4 },
            .{ .start = 2, .end = 4 },
            null,
            .{ .start = 4, .end = 5 },
            null,
            .{ .start = 4, .end = 5 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition67" {
    try executeCase(.{
        .name = "fowler/repetition/repetition67",
        .pattern = "((..)|(.)){1}",
        .input = .{ .haystack = "aaaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_exact = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition68" {
    try executeCase(.{
        .name = "fowler/repetition/repetition68",
        .pattern = "((..)|(.)){2}",
        .input = .{ .haystack = "aaaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 2, .end = 4 },
            .{ .start = 2, .end = 4 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_exact = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition70" {
    try executeCase(.{
        .name = "fowler/repetition/repetition70",
        .pattern = "((..)|(.)){3}",
        .input = .{ .haystack = "aaaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 5 },
            .{ .start = 4, .end = 5 },
            .{ .start = 2, .end = 4 },
            .{ .start = 4, .end = 5 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_exact = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition73" {
    try executeCase(.{
        .name = "fowler/repetition/repetition73",
        .pattern = "((..)|(.))*",
        .input = .{ .haystack = "aaaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 5 },
            .{ .start = 4, .end = 5 },
            .{ .start = 2, .end = 4 },
            .{ .start = 4, .end = 5 },
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition75" {
    try executeCase(.{
        .name = "fowler/repetition/repetition75",
        .pattern = "((..)|(.))",
        .input = .{ .haystack = "aaaaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition76" {
    try executeCase(.{
        .name = "fowler/repetition/repetition76",
        .pattern = "((..)|(.))((..)|(.))",
        .input = .{ .haystack = "aaaaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            null,
            .{ .start = 2, .end = 4 },
            .{ .start = 2, .end = 4 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition77" {
    try executeCase(.{
        .name = "fowler/repetition/repetition77",
        .pattern = "((..)|(.))((..)|(.))((..)|(.))",
        .input = .{ .haystack = "aaaaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            null,
            .{ .start = 2, .end = 4 },
            .{ .start = 2, .end = 4 },
            null,
            .{ .start = 4, .end = 6 },
            .{ .start = 4, .end = 6 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition79" {
    try executeCase(.{
        .name = "fowler/repetition/repetition79",
        .pattern = "((..)|(.)){1}",
        .input = .{ .haystack = "aaaaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            .{ .start = 0, .end = 2 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_exact = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition80" {
    try executeCase(.{
        .name = "fowler/repetition/repetition80",
        .pattern = "((..)|(.)){2}",
        .input = .{ .haystack = "aaaaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 4 },
            .{ .start = 2, .end = 4 },
            .{ .start = 2, .end = 4 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_exact = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition81" {
    try executeCase(.{
        .name = "fowler/repetition/repetition81",
        .pattern = "((..)|(.)){3}",
        .input = .{ .haystack = "aaaaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 4, .end = 6 },
            .{ .start = 4, .end = 6 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_exact = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition83" {
    try executeCase(.{
        .name = "fowler/repetition/repetition83",
        .pattern = "((..)|(.))*",
        .input = .{ .haystack = "aaaaaa", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 4, .end = 6 },
            .{ .start = 4, .end = 6 },
            null,
        },
        .requires = caps.requires(.{ .dot = true, .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive90" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive90",
        .pattern = "X(.?){0,}Y",
        .input = .{ .haystack = "X1234567Y", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 9 },
            .{ .start = 7, .end = 8 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_min = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive91" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive91",
        .pattern = "X(.?){1,}Y",
        .input = .{ .haystack = "X1234567Y", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 9 },
            .{ .start = 7, .end = 8 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_min = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive92" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive92",
        .pattern = "X(.?){2,}Y",
        .input = .{ .haystack = "X1234567Y", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 9 },
            .{ .start = 7, .end = 8 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_min = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive93" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive93",
        .pattern = "X(.?){3,}Y",
        .input = .{ .haystack = "X1234567Y", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 9 },
            .{ .start = 7, .end = 8 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_min = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive94" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive94",
        .pattern = "X(.?){4,}Y",
        .input = .{ .haystack = "X1234567Y", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 9 },
            .{ .start = 7, .end = 8 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_min = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive95" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive95",
        .pattern = "X(.?){5,}Y",
        .input = .{ .haystack = "X1234567Y", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 9 },
            .{ .start = 7, .end = 8 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_min = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive96" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive96",
        .pattern = "X(.?){6,}Y",
        .input = .{ .haystack = "X1234567Y", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 9 },
            .{ .start = 7, .end = 8 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_min = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive97" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive97",
        .pattern = "X(.?){7,}Y",
        .input = .{ .haystack = "X1234567Y", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 9 },
            .{ .start = 7, .end = 8 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_min = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive98" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive98",
        .pattern = "X(.?){8,}Y",
        .input = .{ .haystack = "X1234567Y", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 9 },
            .{ .start = 8, .end = 8 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_min = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive100" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive100",
        .pattern = "X(.?){0,8}Y",
        .input = .{ .haystack = "X1234567Y", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 9 },
            .{ .start = 8, .end = 8 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_range = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive102" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive102",
        .pattern = "X(.?){1,8}Y",
        .input = .{ .haystack = "X1234567Y", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 9 },
            .{ .start = 8, .end = 8 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_range = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive104" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive104",
        .pattern = "X(.?){2,8}Y",
        .input = .{ .haystack = "X1234567Y", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 9 },
            .{ .start = 8, .end = 8 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_range = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive106" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive106",
        .pattern = "X(.?){3,8}Y",
        .input = .{ .haystack = "X1234567Y", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 9 },
            .{ .start = 8, .end = 8 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_range = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive108" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive108",
        .pattern = "X(.?){4,8}Y",
        .input = .{ .haystack = "X1234567Y", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 9 },
            .{ .start = 8, .end = 8 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_range = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive110" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive110",
        .pattern = "X(.?){5,8}Y",
        .input = .{ .haystack = "X1234567Y", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 9 },
            .{ .start = 8, .end = 8 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_range = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive112" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive112",
        .pattern = "X(.?){6,8}Y",
        .input = .{ .haystack = "X1234567Y", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 9 },
            .{ .start = 8, .end = 8 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_range = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive114" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive114",
        .pattern = "X(.?){7,8}Y",
        .input = .{ .haystack = "X1234567Y", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 9 },
            .{ .start = 8, .end = 8 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_range = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive115" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive115",
        .pattern = "X(.?){8,8}Y",
        .input = .{ .haystack = "X1234567Y", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 9 },
            .{ .start = 8, .end = 8 },
        },
        .requires = caps.requires(.{ .dot = true, .rep_zero_or_one = true, .rep_range = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive127" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive127",
        .pattern = "(a|ab|c|bcd){0,}(d*)",
        .input = .{ .haystack = "ababcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 1, .end = 1 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_min = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive129" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive129",
        .pattern = "(a|ab|c|bcd){1,}(d*)",
        .input = .{ .haystack = "ababcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 1, .end = 1 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_min = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive130" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive130",
        .pattern = "(a|ab|c|bcd){2,}(d*)",
        .input = .{ .haystack = "ababcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 3, .end = 6 },
            .{ .start = 6, .end = 6 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_min = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive131" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive131",
        .pattern = "(a|ab|c|bcd){3,}(d*)",
        .input = .{ .haystack = "ababcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 3, .end = 6 },
            .{ .start = 6, .end = 6 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_min = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive132" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive132",
        .pattern = "(a|ab|c|bcd){4,}(d*)",
        .input = .{ .haystack = "ababcd", .anchored = false },
        .expected = &[_]?Match{},
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_min = true }),
    });
}

test "fowler/repetition/repetition-expensive134" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive134",
        .pattern = "(a|ab|c|bcd){0,10}(d*)",
        .input = .{ .haystack = "ababcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 1, .end = 1 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_range = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive136" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive136",
        .pattern = "(a|ab|c|bcd){1,10}(d*)",
        .input = .{ .haystack = "ababcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 1, .end = 1 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_range = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive137" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive137",
        .pattern = "(a|ab|c|bcd){2,10}(d*)",
        .input = .{ .haystack = "ababcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 3, .end = 6 },
            .{ .start = 6, .end = 6 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_range = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive138" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive138",
        .pattern = "(a|ab|c|bcd){3,10}(d*)",
        .input = .{ .haystack = "ababcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 3, .end = 6 },
            .{ .start = 6, .end = 6 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_range = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive139" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive139",
        .pattern = "(a|ab|c|bcd){4,10}(d*)",
        .input = .{ .haystack = "ababcd", .anchored = false },
        .expected = &[_]?Match{},
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_range = true }),
    });
}

test "fowler/repetition/repetition-expensive141" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive141",
        .pattern = "(a|ab|c|bcd)*(d*)",
        .input = .{ .haystack = "ababcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 1, .end = 1 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive143" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive143",
        .pattern = "(a|ab|c|bcd)+(d*)",
        .input = .{ .haystack = "ababcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 1 },
            .{ .start = 0, .end = 1 },
            .{ .start = 1, .end = 1 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive149" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive149",
        .pattern = "(ab|a|c|bcd){0,}(d*)",
        .input = .{ .haystack = "ababcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 4, .end = 5 },
            .{ .start = 5, .end = 6 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_min = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive151" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive151",
        .pattern = "(ab|a|c|bcd){1,}(d*)",
        .input = .{ .haystack = "ababcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 4, .end = 5 },
            .{ .start = 5, .end = 6 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_min = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive153" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive153",
        .pattern = "(ab|a|c|bcd){2,}(d*)",
        .input = .{ .haystack = "ababcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 4, .end = 5 },
            .{ .start = 5, .end = 6 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_min = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive155" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive155",
        .pattern = "(ab|a|c|bcd){3,}(d*)",
        .input = .{ .haystack = "ababcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 4, .end = 5 },
            .{ .start = 5, .end = 6 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_min = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive156" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive156",
        .pattern = "(ab|a|c|bcd){4,}(d*)",
        .input = .{ .haystack = "ababcd", .anchored = false },
        .expected = &[_]?Match{},
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_min = true }),
    });
}

test "fowler/repetition/repetition-expensive158" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive158",
        .pattern = "(ab|a|c|bcd){0,10}(d*)",
        .input = .{ .haystack = "ababcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 4, .end = 5 },
            .{ .start = 5, .end = 6 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_range = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive160" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive160",
        .pattern = "(ab|a|c|bcd){1,10}(d*)",
        .input = .{ .haystack = "ababcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 4, .end = 5 },
            .{ .start = 5, .end = 6 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_range = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive162" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive162",
        .pattern = "(ab|a|c|bcd){2,10}(d*)",
        .input = .{ .haystack = "ababcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 4, .end = 5 },
            .{ .start = 5, .end = 6 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_range = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive164" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive164",
        .pattern = "(ab|a|c|bcd){3,10}(d*)",
        .input = .{ .haystack = "ababcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 4, .end = 5 },
            .{ .start = 5, .end = 6 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_range = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive165" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive165",
        .pattern = "(ab|a|c|bcd){4,10}(d*)",
        .input = .{ .haystack = "ababcd", .anchored = false },
        .expected = &[_]?Match{},
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_range = true }),
    });
}

test "fowler/repetition/repetition-expensive167" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive167",
        .pattern = "(ab|a|c|bcd)*(d*)",
        .input = .{ .haystack = "ababcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 4, .end = 5 },
            .{ .start = 5, .end = 6 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .input_anchored = true }),
    });
}

test "fowler/repetition/repetition-expensive169" {
    try executeCase(.{
        .name = "fowler/repetition/repetition-expensive169",
        .pattern = "(ab|a|c|bcd)+(d*)",
        .input = .{ .haystack = "ababcd", .anchored = true },
        .expected = &[_]?Match{
            .{ .start = 0, .end = 6 },
            .{ .start = 4, .end = 5 },
            .{ .start = 5, .end = 6 },
        },
        .requires = caps.requires(.{ .alternation = true, .rep_zero_or_more = true, .rep_one_or_more = true, .input_anchored = true }),
    });
}
