const harness = @import("../harness.zig");

pub const suite: harness.Suite = .{
    .name = "fowler/repetition",
    .cases = &cases,
};

const cases = [_]harness.Case{
    .{
        .name = "repetition10",
        .pattern = "((..)|(.))",
        .haystack = "",
        .expected = .one(null),
    },
    .{
        .name = "repetition11",
        .pattern = "((..)|(.))((..)|(.))",
        .haystack = "",
        .expected = .one(null),
    },
    .{
        .name = "repetition12",
        .pattern = "((..)|(.))((..)|(.))((..)|(.))",
        .haystack = "",
        .expected = .one(null),
    },
    .{
        .name = "repetition14",
        .pattern = "((..)|(.)){1}",
        .haystack = "",
        .expected = .one(null),
    },
    .{
        .name = "repetition15",
        .pattern = "((..)|(.)){2}",
        .haystack = "",
        .expected = .one(null),
    },
    .{
        .name = "repetition16",
        .pattern = "((..)|(.)){3}",
        .haystack = "",
        .expected = .one(null),
    },
    .{
        .name = "repetition18",
        .pattern = "((..)|(.))*",
        .haystack = "",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 0 }, null, null, null }),
    },
    .{
        .name = "repetition20",
        .pattern = "((..)|(.))",
        .haystack = "a",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 }, null, .{ 0, 1 } }),
    },
    .{
        .name = "repetition21",
        .pattern = "((..)|(.))((..)|(.))",
        .haystack = "a",
        .expected = .one(null),
    },
    .{
        .name = "repetition22",
        .pattern = "((..)|(.))((..)|(.))((..)|(.))",
        .haystack = "a",
        .expected = .one(null),
    },
    .{
        .name = "repetition24",
        .pattern = "((..)|(.)){1}",
        .haystack = "a",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 }, null, .{ 0, 1 } }),
    },
    .{
        .name = "repetition25",
        .pattern = "((..)|(.)){2}",
        .haystack = "a",
        .expected = .one(null),
    },
    .{
        .name = "repetition26",
        .pattern = "((..)|(.)){3}",
        .haystack = "a",
        .expected = .one(null),
    },
    .{
        .name = "repetition28",
        .pattern = "((..)|(.))*",
        .haystack = "a",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 }, null, .{ 0, 1 } }),
    },
    .{
        .name = "repetition30",
        .pattern = "((..)|(.))",
        .haystack = "aa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 0, 2 }, .{ 0, 2 }, null }),
    },
    .{
        .name = "repetition31",
        .pattern = "((..)|(.))((..)|(.))",
        .haystack = "aa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 0, 1 }, null, .{ 0, 1 }, .{ 1, 2 }, null, .{ 1, 2 } }),
    },
    .{
        .name = "repetition32",
        .pattern = "((..)|(.))((..)|(.))((..)|(.))",
        .haystack = "aa",
        .expected = .one(null),
    },
    .{
        .name = "repetition34",
        .pattern = "((..)|(.)){1}",
        .haystack = "aa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 0, 2 }, .{ 0, 2 }, null }),
    },
    .{
        .name = "repetition35",
        .pattern = "((..)|(.)){2}",
        .haystack = "aa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 1, 2 }, null, .{ 1, 2 } }),
    },
    .{
        .name = "repetition36",
        .pattern = "((..)|(.)){3}",
        .haystack = "aa",
        .expected = .one(null),
    },
    .{
        .name = "repetition38",
        .pattern = "((..)|(.))*",
        .haystack = "aa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 0, 2 }, .{ 0, 2 }, null }),
    },
    .{
        .name = "repetition40",
        .pattern = "((..)|(.))",
        .haystack = "aaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 0, 2 }, .{ 0, 2 }, null }),
    },
    .{
        .name = "repetition41",
        .pattern = "((..)|(.))((..)|(.))",
        .haystack = "aaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 3 }, .{ 0, 2 }, .{ 0, 2 }, null, .{ 2, 3 }, null, .{ 2, 3 } }),
    },
    .{
        .name = "repetition42",
        .pattern = "((..)|(.))((..)|(.))((..)|(.))",
        .haystack = "aaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 3 }, .{ 0, 1 }, null, .{ 0, 1 }, .{ 1, 2 }, null, .{ 1, 2 }, .{ 2, 3 }, null, .{ 2, 3 } }),
    },
    .{
        .name = "repetition44",
        .pattern = "((..)|(.)){1}",
        .haystack = "aaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 0, 2 }, .{ 0, 2 }, null }),
    },
    .{
        .name = "repetition46",
        .pattern = "((..)|(.)){2}",
        .haystack = "aaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 3 }, .{ 2, 3 }, .{ 0, 2 }, .{ 2, 3 } }),
    },
    .{
        .name = "repetition47",
        .pattern = "((..)|(.)){3}",
        .haystack = "aaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 3 }, .{ 2, 3 }, null, .{ 2, 3 } }),
    },
    .{
        .name = "repetition50",
        .pattern = "((..)|(.))*",
        .haystack = "aaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 3 }, .{ 2, 3 }, .{ 0, 2 }, .{ 2, 3 } }),
    },
    .{
        .name = "repetition52",
        .pattern = "((..)|(.))",
        .haystack = "aaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 0, 2 }, .{ 0, 2 }, null }),
    },
    .{
        .name = "repetition53",
        .pattern = "((..)|(.))((..)|(.))",
        .haystack = "aaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 0, 2 }, .{ 0, 2 }, null, .{ 2, 4 }, .{ 2, 4 }, null }),
    },
    .{
        .name = "repetition54",
        .pattern = "((..)|(.))((..)|(.))((..)|(.))",
        .haystack = "aaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 0, 2 }, .{ 0, 2 }, null, .{ 2, 3 }, null, .{ 2, 3 }, .{ 3, 4 }, null, .{ 3, 4 } }),
    },
    .{
        .name = "repetition56",
        .pattern = "((..)|(.)){1}",
        .haystack = "aaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 0, 2 }, .{ 0, 2 }, null }),
    },
    .{
        .name = "repetition57",
        .pattern = "((..)|(.)){2}",
        .haystack = "aaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 2, 4 }, .{ 2, 4 }, null }),
    },
    .{
        .name = "repetition59",
        .pattern = "((..)|(.)){3}",
        .haystack = "aaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 3, 4 }, .{ 0, 2 }, .{ 3, 4 } }),
    },
    .{
        .name = "repetition61",
        .pattern = "((..)|(.))*",
        .haystack = "aaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 2, 4 }, .{ 2, 4 }, null }),
    },
    .{
        .name = "repetition63",
        .pattern = "((..)|(.))",
        .haystack = "aaaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 0, 2 }, .{ 0, 2 }, null }),
    },
    .{
        .name = "repetition64",
        .pattern = "((..)|(.))((..)|(.))",
        .haystack = "aaaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 0, 2 }, .{ 0, 2 }, null, .{ 2, 4 }, .{ 2, 4 }, null }),
    },
    .{
        .name = "repetition65",
        .pattern = "((..)|(.))((..)|(.))((..)|(.))",
        .haystack = "aaaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 5 }, .{ 0, 2 }, .{ 0, 2 }, null, .{ 2, 4 }, .{ 2, 4 }, null, .{ 4, 5 }, null, .{ 4, 5 } }),
    },
    .{
        .name = "repetition67",
        .pattern = "((..)|(.)){1}",
        .haystack = "aaaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 0, 2 }, .{ 0, 2 }, null }),
    },
    .{
        .name = "repetition68",
        .pattern = "((..)|(.)){2}",
        .haystack = "aaaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 2, 4 }, .{ 2, 4 }, null }),
    },
    .{
        .name = "repetition70",
        .pattern = "((..)|(.)){3}",
        .haystack = "aaaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 5 }, .{ 4, 5 }, .{ 2, 4 }, .{ 4, 5 } }),
    },
    .{
        .name = "repetition73",
        .pattern = "((..)|(.))*",
        .haystack = "aaaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 5 }, .{ 4, 5 }, .{ 2, 4 }, .{ 4, 5 } }),
    },
    .{
        .name = "repetition75",
        .pattern = "((..)|(.))",
        .haystack = "aaaaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 0, 2 }, .{ 0, 2 }, null }),
    },
    .{
        .name = "repetition76",
        .pattern = "((..)|(.))((..)|(.))",
        .haystack = "aaaaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 0, 2 }, .{ 0, 2 }, null, .{ 2, 4 }, .{ 2, 4 }, null }),
    },
    .{
        .name = "repetition77",
        .pattern = "((..)|(.))((..)|(.))((..)|(.))",
        .haystack = "aaaaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 0, 2 }, .{ 0, 2 }, null, .{ 2, 4 }, .{ 2, 4 }, null, .{ 4, 6 }, .{ 4, 6 }, null }),
    },
    .{
        .name = "repetition79",
        .pattern = "((..)|(.)){1}",
        .haystack = "aaaaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 2 }, .{ 0, 2 }, .{ 0, 2 }, null }),
    },
    .{
        .name = "repetition80",
        .pattern = "((..)|(.)){2}",
        .haystack = "aaaaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 4 }, .{ 2, 4 }, .{ 2, 4 }, null }),
    },
    .{
        .name = "repetition81",
        .pattern = "((..)|(.)){3}",
        .haystack = "aaaaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 4, 6 }, .{ 4, 6 }, null }),
    },
    .{
        .name = "repetition83",
        .pattern = "((..)|(.))*",
        .haystack = "aaaaaa",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 4, 6 }, .{ 4, 6 }, null }),
    },
    .{
        .name = "repetition-expensive90",
        .pattern = "X(.?){0,}Y",
        .haystack = "X1234567Y",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 9 }, .{ 7, 8 } }),
    },
    .{
        .name = "repetition-expensive91",
        .pattern = "X(.?){1,}Y",
        .haystack = "X1234567Y",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 9 }, .{ 7, 8 } }),
    },
    .{
        .name = "repetition-expensive92",
        .pattern = "X(.?){2,}Y",
        .haystack = "X1234567Y",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 9 }, .{ 7, 8 } }),
    },
    .{
        .name = "repetition-expensive93",
        .pattern = "X(.?){3,}Y",
        .haystack = "X1234567Y",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 9 }, .{ 7, 8 } }),
    },
    .{
        .name = "repetition-expensive94",
        .pattern = "X(.?){4,}Y",
        .haystack = "X1234567Y",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 9 }, .{ 7, 8 } }),
    },
    .{
        .name = "repetition-expensive95",
        .pattern = "X(.?){5,}Y",
        .haystack = "X1234567Y",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 9 }, .{ 7, 8 } }),
    },
    .{
        .name = "repetition-expensive96",
        .pattern = "X(.?){6,}Y",
        .haystack = "X1234567Y",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 9 }, .{ 7, 8 } }),
    },
    .{
        .name = "repetition-expensive97",
        .pattern = "X(.?){7,}Y",
        .haystack = "X1234567Y",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 9 }, .{ 7, 8 } }),
    },
    .{
        .name = "repetition-expensive98",
        .pattern = "X(.?){8,}Y",
        .haystack = "X1234567Y",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 9 }, .{ 8, 8 } }),
    },
    .{
        .name = "repetition-expensive100",
        .pattern = "X(.?){0,8}Y",
        .haystack = "X1234567Y",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 9 }, .{ 8, 8 } }),
    },
    .{
        .name = "repetition-expensive102",
        .pattern = "X(.?){1,8}Y",
        .haystack = "X1234567Y",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 9 }, .{ 8, 8 } }),
    },
    .{
        .name = "repetition-expensive104",
        .pattern = "X(.?){2,8}Y",
        .haystack = "X1234567Y",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 9 }, .{ 8, 8 } }),
    },
    .{
        .name = "repetition-expensive106",
        .pattern = "X(.?){3,8}Y",
        .haystack = "X1234567Y",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 9 }, .{ 8, 8 } }),
    },
    .{
        .name = "repetition-expensive108",
        .pattern = "X(.?){4,8}Y",
        .haystack = "X1234567Y",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 9 }, .{ 8, 8 } }),
    },
    .{
        .name = "repetition-expensive110",
        .pattern = "X(.?){5,8}Y",
        .haystack = "X1234567Y",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 9 }, .{ 8, 8 } }),
    },
    .{
        .name = "repetition-expensive112",
        .pattern = "X(.?){6,8}Y",
        .haystack = "X1234567Y",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 9 }, .{ 8, 8 } }),
    },
    .{
        .name = "repetition-expensive114",
        .pattern = "X(.?){7,8}Y",
        .haystack = "X1234567Y",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 9 }, .{ 8, 8 } }),
    },
    .{
        .name = "repetition-expensive115",
        .pattern = "X(.?){8,8}Y",
        .haystack = "X1234567Y",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 9 }, .{ 8, 8 } }),
    },
    .{
        .name = "repetition-expensive127",
        .pattern = "(a|ab|c|bcd){0,}(d*)",
        .haystack = "ababcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 }, .{ 1, 1 } }),
    },
    .{
        .name = "repetition-expensive129",
        .pattern = "(a|ab|c|bcd){1,}(d*)",
        .haystack = "ababcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 }, .{ 1, 1 } }),
    },
    .{
        .name = "repetition-expensive130",
        .pattern = "(a|ab|c|bcd){2,}(d*)",
        .haystack = "ababcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 3, 6 }, .{ 6, 6 } }),
    },
    .{
        .name = "repetition-expensive131",
        .pattern = "(a|ab|c|bcd){3,}(d*)",
        .haystack = "ababcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 3, 6 }, .{ 6, 6 } }),
    },
    .{
        .name = "repetition-expensive132",
        .pattern = "(a|ab|c|bcd){4,}(d*)",
        .haystack = "ababcd",
        .expected = .one(null),
    },
    .{
        .name = "repetition-expensive134",
        .pattern = "(a|ab|c|bcd){0,10}(d*)",
        .haystack = "ababcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 }, .{ 1, 1 } }),
    },
    .{
        .name = "repetition-expensive136",
        .pattern = "(a|ab|c|bcd){1,10}(d*)",
        .haystack = "ababcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 }, .{ 1, 1 } }),
    },
    .{
        .name = "repetition-expensive137",
        .pattern = "(a|ab|c|bcd){2,10}(d*)",
        .haystack = "ababcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 3, 6 }, .{ 6, 6 } }),
    },
    .{
        .name = "repetition-expensive138",
        .pattern = "(a|ab|c|bcd){3,10}(d*)",
        .haystack = "ababcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 3, 6 }, .{ 6, 6 } }),
    },
    .{
        .name = "repetition-expensive139",
        .pattern = "(a|ab|c|bcd){4,10}(d*)",
        .haystack = "ababcd",
        .expected = .one(null),
    },
    .{
        .name = "repetition-expensive141",
        .pattern = "(a|ab|c|bcd)*(d*)",
        .haystack = "ababcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 }, .{ 1, 1 } }),
    },
    .{
        .name = "repetition-expensive143",
        .pattern = "(a|ab|c|bcd)+(d*)",
        .haystack = "ababcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 1 }, .{ 0, 1 }, .{ 1, 1 } }),
    },
    .{
        .name = "repetition-expensive149",
        .pattern = "(ab|a|c|bcd){0,}(d*)",
        .haystack = "ababcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 4, 5 }, .{ 5, 6 } }),
    },
    .{
        .name = "repetition-expensive151",
        .pattern = "(ab|a|c|bcd){1,}(d*)",
        .haystack = "ababcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 4, 5 }, .{ 5, 6 } }),
    },
    .{
        .name = "repetition-expensive153",
        .pattern = "(ab|a|c|bcd){2,}(d*)",
        .haystack = "ababcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 4, 5 }, .{ 5, 6 } }),
    },
    .{
        .name = "repetition-expensive155",
        .pattern = "(ab|a|c|bcd){3,}(d*)",
        .haystack = "ababcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 4, 5 }, .{ 5, 6 } }),
    },
    .{
        .name = "repetition-expensive156",
        .pattern = "(ab|a|c|bcd){4,}(d*)",
        .haystack = "ababcd",
        .expected = .one(null),
    },
    .{
        .name = "repetition-expensive158",
        .pattern = "(ab|a|c|bcd){0,10}(d*)",
        .haystack = "ababcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 4, 5 }, .{ 5, 6 } }),
    },
    .{
        .name = "repetition-expensive160",
        .pattern = "(ab|a|c|bcd){1,10}(d*)",
        .haystack = "ababcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 4, 5 }, .{ 5, 6 } }),
    },
    .{
        .name = "repetition-expensive162",
        .pattern = "(ab|a|c|bcd){2,10}(d*)",
        .haystack = "ababcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 4, 5 }, .{ 5, 6 } }),
    },
    .{
        .name = "repetition-expensive164",
        .pattern = "(ab|a|c|bcd){3,10}(d*)",
        .haystack = "ababcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 4, 5 }, .{ 5, 6 } }),
    },
    .{
        .name = "repetition-expensive165",
        .pattern = "(ab|a|c|bcd){4,10}(d*)",
        .haystack = "ababcd",
        .expected = .one(null),
    },
    .{
        .name = "repetition-expensive167",
        .pattern = "(ab|a|c|bcd)*(d*)",
        .haystack = "ababcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 4, 5 }, .{ 5, 6 } }),
    },
    .{
        .name = "repetition-expensive169",
        .pattern = "(ab|a|c|bcd)+(d*)",
        .haystack = "ababcd",
        .anchored = true,
        .expected = .capt(&.{ .{ 0, 6 }, .{ 4, 5 }, .{ 5, 6 } }),
    },
};
