//! Defines the NFA.
//!
//! This is generated by the Compiler. User of this struct is expected to call Program.deinit()
//! to release resources.

const Program = @This();

/// Contains all states of the NFA graph.
states: []const State,
/// See State.ranges.
ranges: []const ByteRange,
/// See State.alt.
branches: []const State.Id,
arena: std.heap.ArenaAllocator,

/// Useful to determine the upper bound of allocated ThreadList size.
matcher_count: u32,
capture_info: CaptureInfo,

pub fn deinit(p: *Program) void {
    p.capture_info.deinit();
    p.arena.deinit();
}

pub fn literalPrefix(p: *const Program) ?u8 {
    if (p.states.len < 2) return null;
    var id: usize = 0;
    while (true) {
        switch (p.states[id]) {
            .char => |s| return s.byte,
            .capture => |s| id = s.out,
            .empty => |s| id = s.out,
            else => return null,
        }
    }
}

/// Index type for metadata arrays (such as Program.ranges or .branches).
/// Typically Index and Length are used together as a `slice` into metadata arrays.
pub const Index = u32;
/// Length type for metadata arrays (such as Program.ranges or .branches).
/// Typically Index and Length are used together as a `slice` into metadata arrays.
pub const Length = u16;

/// Position of a character into input `haystack`.
/// It is sized as `u31` so `?Offset` fits in 32 bits for capture slot storage.
/// Implementation note: If this turns out to be too restrictive, a sentinel offset value
/// can be used instead.
pub const Offset = u31;

/// ByteRange is inclusive on both ends.
pub const ByteRange = struct {
    from: u8,
    to: u8,

    pub fn contains(self: ByteRange, byte: u8) bool {
        return self.from <= byte and byte <= self.to;
    }
};

pub const StateId = State.Id;

pub const State = union(enum) {
    /// Contains a single byte, which must equal the current input to transition to the next state.
    char: struct { byte: u8, out: Id },

    /// Points to a list of ByteRange, one of which the current input must belong to in
    /// order to transition to the next state.
    ///
    /// Instead of scattering these lists in memory, they're stored together in Program.ranges array.
    /// This state then stores the slice into the common array.
    ranges: struct { start: Index, len: Length, negated: bool, out: Id },

    /// Consumes any input character and conditionally transitions to the next state
    /// based on `kind`.
    any: Any,

    /// Unconditional epsilon transition that does not consume any input character.
    empty: struct { out: Id },

    /// Conditional epsilon transition that does not consume input, instead it makes a look-around
    /// assertion about the input. The predicate is evaluated during the process of "epsilon closure",
    /// which computes the next set of reachable states.
    assert: Assertion,

    /// Unconditional epsilon transition that carries the capture slot information (2k or 2k+1).
    capture: struct { slot: Index, out: Id },

    /// This state indicates epsilon transition to a list of states (branches), where matches found
    /// in earlier branches are preferred over later.
    ///
    /// Instead of scattering these lists in memory, they're stored together in Program.branches array.
    /// This state then stores the slice into the common array.
    alt: struct { start: Index, len: Length },

    /// This is a common special case of State.alt where there are only two alternates, where matches found
    /// via `left` are preferred over matches found via `right`, in order to save an additional memory access.
    alt2: struct { left: Id, right: Id },

    /// There is no transition out of this state.
    fail,

    /// The accepting state.
    match,

    /// Index into Program.states
    pub const Id = u32;

    pub const Any = struct {
        kind: Kind,
        out: Id,

        pub const Kind = enum {
            all,
            not_lf,
        };
    };

    pub const Assertion = struct {
        pred: Predicate,
        out: Id,

        pub const Predicate = enum {
            start_text,
            end_text,
            start_line,
            end_line,
            word_boundary,
            not_word_boundary,
        };
    };
};

pub fn dump(prog: Program, w: *std.Io.Writer) !void {
    try w.writeAll("States\n");
    for (prog.states, 0..) |state, i| {
        switch (state) {
            .char => |pl| try w.print(
                "{d:>3} {s:<8} byte={c}  out={d:<3}\n",
                .{ i, @tagName(state), pl.byte, pl.out },
            ),
            .ranges => |pl| {
                try w.print(
                    "{d:>3} {s:<8}         out={d:<3}  start={d:<3} len={d:<3}\n",
                    .{ i, @tagName(state), pl.out, pl.start, pl.len },
                );
            },
            .any => |pl| try w.print("{d:>3} {s:<8}         out={d:<3}  kind={s}\n", .{ i, @tagName(state), pl.out, @tagName(pl.kind) }),
            .empty => |pl| try w.print("{d:>3} {s:<8}         out={d:<3}\n", .{ i, @tagName(state), pl.out }),
            .assert => |pl| try w.print("{d:>3} {s:<8}         out={d:<3}  pred={s}\n", .{ i, @tagName(state), pl.out, @tagName(pl.pred) }),
            .alt => |pl| {
                try w.print(
                    "{d:>3} {s:<8}                  start={d:<3} len={d:<3}",
                    .{ i, @tagName(state), pl.start, pl.len },
                );
                try w.writeAll("  [ ");
                for (prog.branches[pl.start..][0..pl.len]) |out_idx| {
                    try w.print("{d} ", .{out_idx});
                }
                try w.writeAll("]\n");
            },
            .alt2 => |pl| {
                try w.print(
                    "{d:>3} {s:<8}         left={d:<3} right={d:<3}\n",
                    .{ i, @tagName(state), pl.left, pl.right },
                );
            },
            .capture => |pl| try w.print(
                "{d:>3} {s:<8} slot={d}  out={d:<3}\n",
                .{ i, @tagName(state), pl.slot, pl.out },
            ),
            .match => try w.print("{d:>3} {s:<8}\n", .{ i, @tagName(state) }),
            .fail => try w.print("{d:>3} {s:<8}\n", .{ i, @tagName(state) }),
        }
    }

    // std.debug.print("\nRanges:\n", .{});
    // for (prog.ranges, 0..) |range, i| {
    //     std.debug.print("{d:>3} {{ from = {c}, to = {c} }}\n", .{ i, range.from, range.to });
    // }
}

const std = @import("std");

const CaptureInfo = @import("CaptureInfo.zig");
